"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoint_models.py` script.
"""

from pydantic import BaseModel, ConfigDict


class Filter5(BaseModel):
    """Filter5.

    Filters for fields with types: ['int']
    and lookup types: ['gt', 'gte', 'isnull', 'lt', 'lte', 'range']
    """

    model_config = ConfigDict(extra="forbid")
    gt: None | int = None
    gte: None | int = None
    isnull: None | bool = None
    lt: None | int = None
    lte: None | int = None
    range: None | tuple[int, int] = None
