"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoint_models.py` script.
"""

from datetime import datetime

from pydantic import BaseModel, ConfigDict


class Filter7(BaseModel):
    """Filter7.

    Filters for fields with types: ['datetime']
    and lookup types: ['day', 'gt', 'gte', 'hour', 'lt', 'lte', 'minute', 'month', 'range', 'second', 'year']
    """

    model_config = ConfigDict(extra="forbid")
    day: None | int = None
    gt: None | datetime = None
    gte: None | datetime = None
    hour: None | int = None
    lt: None | datetime = None
    lte: None | datetime = None
    minute: None | int = None
    month: None | int = None
    range: None | tuple[datetime, datetime] = None
    second: None | int = None
    year: None | int = None
