"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoint_models.py` script.
"""

from pydantic import BaseModel, ConfigDict


class Filter1(BaseModel):
    """Filter1.

    Filters for fields with types: ['str']
    and lookup types: ['startswith']
    """

    model_config = ConfigDict(extra="forbid")
    startswith: None | str = None
