"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoint_models.py` script.
"""

from pydantic import BaseModel, ConfigDict


class Filter3(BaseModel):
    """Filter3.

    Filters for fields with types: ['int']
    and lookup types: ['gt', 'gte', 'lt', 'lte']
    """

    model_config = ConfigDict(extra="forbid")
    gt: None | int = None
    gte: None | int = None
    lt: None | int = None
    lte: None | int = None
