"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoint_models.py` script.
"""

from datetime import date

from pydantic import BaseModel, ConfigDict


class Filter6(BaseModel):
    """Filter6.

    Filters for fields with types: ['date']
    and lookup types: ['day', 'gt', 'gte', 'lt', 'lte', 'month', 'range', 'year']
    """

    model_config = ConfigDict(extra="forbid")
    day: None | int = None
    gt: None | date = None
    gte: None | date = None
    lt: None | date = None
    lte: None | date = None
    month: None | int = None
    range: None | tuple[date, date] = None
    year: None | int = None
