"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from pydantic import BaseModel


class Filter2(BaseModel):
    """Filter2.

    Filters for fields with types: ['int']
    and lookup types: ['gt', 'gte', 'lt', 'lte']
    """

    gt: None | int = None
    gte: None | int = None
    lt: None | int = None
    lte: None | int = None
