"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoint_models.py` script.
"""

from pydantic import BaseModel, ConfigDict


class Filter2(BaseModel):
    """Filter2.

    Filters for fields with types: ['str']
    and lookup types: ['iexact', 'istartswith', 'startswith']
    """

    model_config = ConfigDict(extra="forbid")
    iexact: None | str = None
    istartswith: None | str = None
    startswith: None | str = None
