"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from pydantic import BaseModel


class Filter3(BaseModel):
    """Filter3.

    Filters for fields with types: ['int']
    and lookup types: ['gt', 'gte', 'lt', 'lte', 'range']
    """

    gt: None | int = None
    gte: None | int = None
    lt: None | int = None
    lte: None | int = None
    range: None | tuple[int, int] = None
