"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, ClassVar

from pydantic import BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter8
from courtlistener.utils import (
    choice_validator,
)


class AbaRatingsEndpoint(Endpoint):
    """Aba Ratings Endpoint"""

    endpoint: ClassVar[str] = "/aba-ratings/"
    endpoint_id: ClassVar[str] = "aba-ratings"
    endpoint_name: ClassVar[str] = "Aba Ratings"

    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    year_rated: Annotated[
        None | int,
        Field(
            None,
            description="The year of the rating.",
        ),
    ]
    rating: Annotated[
        None | str,
        Field(
            None,
            description="The rating given to the person.",
            json_schema_extra={
                "choices": [
                    {
                        "value": "ewq",
                        "display_name": "Exceptionally Well Qualified",
                    },
                    {"value": "wq", "display_name": "Well Qualified"},
                    {"value": "q", "display_name": "Qualified"},
                    {"value": "nq", "display_name": "Not Qualified"},
                    {
                        "value": "nqa",
                        "display_name": "Not Qualified By Reason of Age",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    person: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {
                        "value": "year_rated",
                        "display_name": "Year Rated (asc)",
                    },
                    {
                        "value": "-year_rated",
                        "display_name": "Year Rated (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
