"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter4
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class AlertsEndpoint(Endpoint):
    """Alerts Endpoint"""

    endpoint: ClassVar[str] = "/alerts/"
    endpoint_id: ClassVar[str] = "alerts"
    endpoint_name: ClassVar[str] = "Alerts"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter field returned in the response.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "alert_type", "display_name": "Alert type"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {
                        "value": "date_last_hit",
                        "display_name": "Time of last trigger",
                    },
                    {"value": "name", "display_name": "A name for the alert"},
                    {
                        "value": "query",
                        "display_name": "The text of an alert created by a user",
                    },
                    {
                        "value": "rate",
                        "display_name": "The rate chosen by the user for the alert",
                    },
                    {
                        "value": "secret_key",
                        "display_name": "A key to be used in links to access the alert without having to log in. Can be used for a variety of purposes.",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    name: Annotated[
        None | str | Filter4,
        Field(
            None,
        ),
    ]
    query: Annotated[
        None | str | Filter4,
        Field(
            None,
        ),
    ]
    rate: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "rt", "display_name": "Real Time"},
                    {"value": "dly", "display_name": "Daily"},
                    {"value": "wly", "display_name": "Weekly"},
                    {"value": "mly", "display_name": "Monthly"},
                    {"value": "off", "display_name": "Off"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {"value": "name", "display_name": "Name (asc)"},
                    {"value": "-name", "display_name": "Name (desc)"},
                    {"value": "rate", "display_name": "Rate (asc)"},
                    {"value": "-rate", "display_name": "Rate (desc)"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
