"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter4
from courtlistener.utils import (
    choice_validator,
)


class AlertsEndpoint(Endpoint):
    """Alerts Endpoint"""

    endpoint: ClassVar[str] = "/alerts/"
    endpoint_id: ClassVar[str] = "alerts"
    endpoint_name: ClassVar[str] = "Alerts"

    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    name: Annotated[
        None | str | Filter4,
        Field(
            None,
        ),
    ]
    query: Annotated[
        None | str | Filter4,
        Field(
            None,
        ),
    ]
    rate: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "rt", "display_name": "Real Time"},
                    {"value": "dly", "display_name": "Daily"},
                    {"value": "wly", "display_name": "Weekly"},
                    {"value": "mly", "display_name": "Monthly"},
                    {"value": "off", "display_name": "Off"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {"value": "name", "display_name": "Name (asc)"},
                    {"value": "-name", "display_name": "Name (desc)"},
                    {"value": "rate", "display_name": "Rate (asc)"},
                    {"value": "-rate", "display_name": "Rate (desc)"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
