"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_models.py` script.
"""

from typing import ClassVar

from courtlistener.models.endpoint import Endpoint


class ApiUsageEndpoint(Endpoint):
    """Api Usage Endpoint"""

    endpoint: ClassVar[str] = "/api-usage/"
    endpoint_id: ClassVar[str] = "api-usage"
    endpoint_name: ClassVar[str] = "Api Usage"
