"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoint_models.py` script.
"""

from datetime import date, datetime
from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter4, Filter6, Filter7
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    multiple_choice_validator,
    related_validator,
)


class AudioEndpoint(Endpoint):
    """Audio Endpoint"""

    endpoint: ClassVar[str] = "/audio/"
    endpoint_id: ClassVar[str] = "audio"
    endpoint_name: ClassVar[str] = "Audio"

    fields: Annotated[
        None | str | list[str],
        Field(
            None,
            description="Filter which fields are returned.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "absolute_url", "display_name": "Absolute url"},
                    {"value": "panel", "display_name": "Panel"},
                    {"value": "docket", "display_name": "Docket"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "source", "display_name": "Source"},
                    {
                        "value": "case_name_short",
                        "display_name": "Case name short",
                    },
                    {"value": "case_name", "display_name": "Case name"},
                    {
                        "value": "case_name_full",
                        "display_name": "Case name full",
                    },
                    {"value": "judges", "display_name": "Judges"},
                    {"value": "sha1", "display_name": "Sha1"},
                    {"value": "download_url", "display_name": "Download url"},
                    {
                        "value": "local_path_mp3",
                        "display_name": "Local path mp3",
                    },
                    {
                        "value": "local_path_original_file",
                        "display_name": "Local path original file",
                    },
                    {"value": "filepath_ia", "display_name": "Filepath ia"},
                    {
                        "value": "ia_upload_failure_count",
                        "display_name": "Ia upload failure count",
                    },
                    {"value": "duration", "display_name": "Duration"},
                    {
                        "value": "processing_complete",
                        "display_name": "Processing complete",
                    },
                    {"value": "date_blocked", "display_name": "Date blocked"},
                    {"value": "blocked", "display_name": "Blocked"},
                    {
                        "value": "stt_status",
                        "display_name": "Speech to text status",
                    },
                    {
                        "value": "stt_source",
                        "display_name": "Speech to text source",
                    },
                    {
                        "value": "stt_transcript",
                        "display_name": "Speech to text transcription",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
    ]
    id: Annotated[
        None | int | Filter4,
        Field(
            None,
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter7,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter7,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    sha1: Annotated[
        None | str,
        Field(
            None,
            description="unique ID for the document, as generated via SHA1 of the binary file or text data",
        ),
    ]
    blocked: Annotated[
        None | bool,
        Field(
            None,
            description="Should this item be blocked from indexing by search engines?",
        ),
    ]
    date_blocked: Annotated[
        None | date | Filter6,
        Field(
            None,
            description="The date that this opinion was blocked from indexing by search engines",
        ),
    ]
    processing_complete: Annotated[
        None | bool,
        Field(
            None,
            description="Is audio for this item done processing?",
        ),
    ]
    stt_status: Annotated[
        None | int | Filter4,
        Field(
            None,
            description="The status of the Speech to Text for this item?",
            json_schema_extra={
                "choices": [
                    {"value": 0, "display_name": "Speech to Text Needed"},
                    {"value": 1, "display_name": "Speech to Text Complete"},
                    {"value": 2, "display_name": "Speech to Text Failed"},
                    {
                        "value": 3,
                        "display_name": "Transcription does not match audio",
                    },
                    {
                        "value": 4,
                        "display_name": "File size is bigger than 25 MB",
                    },
                    {"value": 5, "display_name": "File does not exist"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    docket: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            description="Related filter: pass a dockets record\u0027s id, or a dict of dockets sub-filters (sent as docket__\u003csubfilter\u003e lookups). Not an enumerated choice field.",
            json_schema_extra={
                "related_class_name": "DocketsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    source: Annotated[
        None | str | list[str],
        Field(
            None,
            description="the source of the audio file, one of: C (court website), H (brad heath archive)",
            json_schema_extra={
                "choices": [
                    {"value": "C", "display_name": "court website"},
                    {"value": "H", "display_name": "brad heath archive"},
                ],
            },
        ),
        BeforeValidator(multiple_choice_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {
                        "value": "date_blocked",
                        "display_name": "Date Blocked (asc)",
                    },
                    {
                        "value": "-date_blocked",
                        "display_name": "Date Blocked (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
