"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.utils import (
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class BankruptcyInformationEndpoint(Endpoint):
    """Bankruptcy Information Endpoint"""

    endpoint: ClassVar[str] = "/bankruptcy-information/"
    endpoint_id: ClassVar[str] = "bankruptcy-information"
    endpoint_name: ClassVar[str] = "Bankruptcy Information"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter field returned in the response.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {
                        "value": "date_converted",
                        "display_name": "Date converted",
                    },
                    {
                        "value": "date_last_to_file_claims",
                        "display_name": "Date last to file claims",
                    },
                    {
                        "value": "date_last_to_file_govt",
                        "display_name": "Date last to file govt",
                    },
                    {
                        "value": "date_debtor_dismissed",
                        "display_name": "Date debtor dismissed",
                    },
                    {"value": "chapter", "display_name": "Chapter"},
                    {"value": "trustee_str", "display_name": "Trustee str"},
                    {"value": "docket", "display_name": "Docket"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
