"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class DocketAlertsEndpoint(Endpoint):
    """Docket Alerts Endpoint"""

    endpoint: ClassVar[str] = "/docket-alerts/"
    endpoint_id: ClassVar[str] = "docket-alerts"
    endpoint_name: ClassVar[str] = "Docket Alerts"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "ID"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {
                        "value": "date_last_hit",
                        "display_name": "Time of last trigger",
                    },
                    {
                        "value": "secret_key",
                        "display_name": "A key to be used in links to access the alert without having to log in. Can be used for a variety of purposes.",
                    },
                    {"value": "alert_type", "display_name": "Alert type"},
                    {"value": "docket", "display_name": "Docket"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    alert_type: Annotated[
        None | int,
        Field(
            None,
            description="The subscription type assigned, Unsubscription or Subscription.",
            json_schema_extra={
                "choices": [
                    {"value": 0, "display_name": "Unsubscription"},
                    {"value": 1, "display_name": "Subscription"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    docket: Annotated[
        None | int,
        Field(
            None,
            description="The docket that we are subscribed to.",
        ),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
