"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import date, datetime
from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter5, Filter7, Filter8
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
    related_validator,
)


class DocketEntriesEndpoint(Endpoint):
    """Docket Entries Endpoint"""

    endpoint: ClassVar[str] = "/docket-entries/"
    endpoint_id: ClassVar[str] = "docket-entries"
    endpoint_name: ClassVar[str] = "Docket Entries"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter which fields are returned.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "docket", "display_name": "Docket"},
                    {
                        "value": "recap_documents",
                        "display_name": "Recap documents",
                    },
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "date_filed", "display_name": "Date filed"},
                    {"value": "time_filed", "display_name": "Time filed"},
                    {"value": "entry_number", "display_name": "Entry number"},
                    {
                        "value": "recap_sequence_number",
                        "display_name": "Recap sequence number",
                    },
                    {
                        "value": "pacer_sequence_number",
                        "display_name": "Pacer sequence number",
                    },
                    {"value": "description", "display_name": "Description"},
                    {"value": "tags", "display_name": "Tags"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    entry_number: Annotated[
        None | int | Filter5,
        Field(
            None,
            description="# on the PACER docket page. For appellate cases, this may be the internal PACER ID for the document, when an entry ID is otherwise unavailable.",
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    date_filed: Annotated[
        None | date | Filter7,
        Field(
            None,
            description="The created date of the Docket Entry according to the court timezone.",
        ),
    ]
    pacer_sequence_number: Annotated[
        None | int | Filter5,
        Field(
            None,
            description="The de_seqno value pulled out of dockets, RSS feeds, and sundry other pages in PACER. The place to find this is currently in the onclick attribute of the links in PACER. Because we do not have this value for all items in the DB, we do not use this value for anything. Still, we collect it for good measure.",
        ),
    ]
    docket: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "DocketsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    recap_documents: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "RecapDocumentsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    tags: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            description="The tags associated with the docket entry.",
            json_schema_extra={
                "related_class_name": "TagsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {
                        "value": "date_filed",
                        "display_name": "Date Filed (asc)",
                    },
                    {
                        "value": "-date_filed",
                        "display_name": "Date Filed (desc)",
                    },
                    {
                        "value": "recap_sequence_number",
                        "display_name": "Recap Sequence Number (asc)",
                    },
                    {
                        "value": "-recap_sequence_number",
                        "display_name": "Recap Sequence Number (desc)",
                    },
                    {
                        "value": "entry_number",
                        "display_name": "Entry Number (asc)",
                    },
                    {
                        "value": "-entry_number",
                        "display_name": "Entry Number (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
