"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter6, Filter8
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
    related_validator,
)


class FinancialDisclosuresEndpoint(Endpoint):
    """Financial Disclosures Endpoint"""

    endpoint: ClassVar[str] = "/financial-disclosures/"
    endpoint_id: ClassVar[str] = "financial-disclosures"
    endpoint_name: ClassVar[str] = "Financial Disclosures"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "agreements", "display_name": "Agreements"},
                    {"value": "debts", "display_name": "Debts"},
                    {"value": "gifts", "display_name": "Gifts"},
                    {"value": "investments", "display_name": "Investments"},
                    {
                        "value": "non_investment_incomes",
                        "display_name": "Non investment incomes",
                    },
                    {"value": "positions", "display_name": "Positions"},
                    {
                        "value": "reimbursements",
                        "display_name": "Reimbursements",
                    },
                    {
                        "value": "spouse_incomes",
                        "display_name": "Spouse incomes",
                    },
                    {"value": "person", "display_name": "Person"},
                    {"value": "filepath", "display_name": "Filepath"},
                    {"value": "thumbnail", "display_name": "Thumbnail"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "year", "display_name": "Year"},
                    {
                        "value": "thumbnail_status",
                        "display_name": "Thumbnail status",
                    },
                    {"value": "page_count", "display_name": "Page count"},
                    {"value": "sha1", "display_name": "Sha1"},
                    {"value": "report_type", "display_name": "Report type"},
                    {"value": "is_amended", "display_name": "Is amended"},
                    {
                        "value": "addendum_content_raw",
                        "display_name": "Addendum content raw",
                    },
                    {
                        "value": "addendum_redacted",
                        "display_name": "Addendum redacted",
                    },
                    {
                        "value": "has_been_extracted",
                        "display_name": "Has been extracted",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    person: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "PeopleEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    addendum_content_raw: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Raw content of addendum with whitespace preserved.",
        ),
    ]
    has_been_extracted: Annotated[
        None | bool,
        Field(
            None,
            description="Have we successfully extracted the data from PDF?",
        ),
    ]
    agreements: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "AgreementsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    debts: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "DebtsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    gifts: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "GiftsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    investments: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "InvestmentsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    non_investment_incomes: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "NonInvestmentIncomesEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    positions: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "PositionsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    reimbursements: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "ReimbursementsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    spouse_incomes: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "SpouseIncomesEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
