"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import date, datetime
from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter4, Filter7, Filter8
from courtlistener.utils import (
    in_post_validator,
    in_pre_validator,
    multiple_choice_validator,
    try_coerce_ints,
)


class FjcIntegratedDatabaseEndpoint(Endpoint):
    """Fjc Integrated Database Endpoint"""

    endpoint: ClassVar[str] = "/fjc-integrated-database/"
    endpoint_id: ClassVar[str] = "fjc-integrated-database"
    endpoint_name: ClassVar[str] = "Fjc Integrated Database"

    dataset_source: Annotated[
        None | int | list[int],
        Field(
            None,
            description="IDB has several source datafiles. This field helps keep track of where a row came from originally.",
            json_schema_extra={
                "choices": [
                    {
                        "value": 1,
                        "display_name": "Civil cases filed and terminated from SY 1970 through SY 1987",
                    },
                    {
                        "value": 2,
                        "display_name": "Civil cases filed, terminated, and pending from SY 1988 to present (2017)",
                    },
                    {
                        "value": 8,
                        "display_name": "Civil cases filed, terminated, and pending from SY 1988 to present (2020)",
                    },
                    {
                        "value": 9,
                        "display_name": "Civil cases filed, terminated, and pending from SY 1988 to present (September 2021)",
                    },
                    {
                        "value": 10,
                        "display_name": "Civil cases filed, terminated, and pending from SY 1988 to present (March 2022)",
                    },
                    {
                        "value": 3,
                        "display_name": "Criminal defendants filed and terminated from SY 1970 through FY 1995",
                    },
                    {
                        "value": 4,
                        "display_name": "Criminal defendants filed, terminated, and pending from FY 1996 to present (2017)",
                    },
                    {
                        "value": 5,
                        "display_name": "Appellate cases filed and terminated from SY 1971 through FY 2007",
                    },
                    {
                        "value": 6,
                        "display_name": "Appellate cases filed, terminated, and pending from FY 2008 to present (2017)",
                    },
                    {
                        "value": 7,
                        "display_name": "Bankruptcy cases filed, terminated, and pending from FY 2008 to present (2017)",
                    },
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(try_coerce_ints),
        BeforeValidator(in_pre_validator),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    circuit: Annotated[
        None | int,
        Field(
            None,
            description="Circuit in which the case was filed.",
        ),
    ]
    district: Annotated[
        None | int,
        Field(
            None,
            description="District court in which the case was filed.",
        ),
    ]
    origin: Annotated[
        None | int | list[int],
        Field(
            None,
            description="A single digit code describing the manner in which the case was filed in the district.",
            json_schema_extra={
                "choices": [
                    {"value": 1, "display_name": "Original Proceeding"},
                    {
                        "value": 2,
                        "display_name": "Removed  (began in the state court, removed to the district court)",
                    },
                    {
                        "value": 3,
                        "display_name": "Remanded for further action (removal from court of appeals)",
                    },
                    {
                        "value": 4,
                        "display_name": "Reinstated/reopened (previously opened and closed, reopened for additional action)",
                    },
                    {
                        "value": 5,
                        "display_name": "Transferred from another district(pursuant to 28 USC 1404)",
                    },
                    {
                        "value": 6,
                        "display_name": "Multi district litigation (cases transferred to this district by an order entered by Judicial Panel on Multi District Litigation pursuant to 28 USC 1407)",
                    },
                    {
                        "value": 7,
                        "display_name": "Appeal to a district judge of a magistrate judge's decision",
                    },
                    {"value": 8, "display_name": "Second reopen"},
                    {"value": 9, "display_name": "Third reopen"},
                    {"value": 10, "display_name": "Fourth reopen"},
                    {"value": 11, "display_name": "Fifth reopen"},
                    {"value": 12, "display_name": "Sixth reopen"},
                    {
                        "value": 13,
                        "display_name": "Multi district litigation originating in the district (valid beginning July 1, 2016)",
                    },
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(try_coerce_ints),
        BeforeValidator(in_pre_validator),
    ]
    date_filed: Annotated[
        None | date | Filter7,
        Field(
            None,
            description="The date on which the case was filed in the district.",
        ),
    ]
    jurisdiction: Annotated[
        None | int | list[int],
        Field(
            None,
            description="The code which provides the basis for the U.S. district court jurisdiction in the case. This code is used in conjunction with appropriate nature of suit code.",
            json_schema_extra={
                "choices": [
                    {"value": 1, "display_name": "Government plaintiff"},
                    {"value": 2, "display_name": "Government defendant"},
                    {"value": 3, "display_name": "Federal question"},
                    {"value": 4, "display_name": "Diversity of citizenship"},
                    {"value": 5, "display_name": "Local question"},
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(try_coerce_ints),
        BeforeValidator(in_pre_validator),
    ]
    title: Annotated[
        None | str | Filter4,
        Field(
            None,
            description="No description provided by FJC.",
        ),
    ]
    section: Annotated[
        None | str | Filter4,
        Field(
            None,
            description="No description provided by FJC.",
        ),
    ]
    subsection: Annotated[
        None | str | Filter4,
        Field(
            None,
            description="No description provided by FJC.",
        ),
    ]
    arbitration_at_filing: Annotated[
        None | str | list[str],
        Field(
            None,
            description="This field is used only by the courts  participating in the Formal Arbitration Program.  It is not used for any other purpose.",
            json_schema_extra={
                "choices": [
                    {"value": "M", "display_name": "Mandatory"},
                    {"value": "V", "display_name": "Voluntary"},
                    {"value": "E", "display_name": "Exempt"},
                    {"value": "Y", "display_name": "Yes, but type unknown"},
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(in_pre_validator),
    ]
    arbitration_at_termination: Annotated[
        None | str | list[str],
        Field(
            None,
            description="Termination arbitration code.",
            json_schema_extra={
                "choices": [
                    {"value": "M", "display_name": "Mandatory"},
                    {"value": "V", "display_name": "Voluntary"},
                    {"value": "E", "display_name": "Exempt"},
                    {"value": "Y", "display_name": "Yes, but type unknown"},
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(in_pre_validator),
    ]
    class_action: Annotated[
        None | bool | list[bool],
        Field(
            None,
            description='Involves an allegation by the plaintiff that the complaint meets the prerequisites of a "Class Action" as provided in Rule 23 - F.R.CV.P. ',
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(in_pre_validator),
    ]
    plaintiff: Annotated[
        None | str | Filter4,
        Field(
            None,
            description="First listed plaintiff. This field appears to be cut off at 30 characters",
        ),
    ]
    defendant: Annotated[
        None | str | Filter4,
        Field(
            None,
            description="First listed defendant. This field appears to be cut off at 30 characters.",
        ),
    ]
    termination_class_action_status: Annotated[
        None | int | list[int],
        Field(
            None,
            description="A code that indicates a case involving allegations of class action.",
            json_schema_extra={
                "choices": [
                    {"value": 2, "display_name": "Denied"},
                    {"value": 3, "display_name": "Granted"},
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(try_coerce_ints),
        BeforeValidator(in_pre_validator),
    ]
    procedural_progress: Annotated[
        None | str | list[str],
        Field(
            None,
            description="The point to which the case had progressed when it was disposed of. See notes in codebook.",
            json_schema_extra={
                "choices": [
                    {
                        "value": "Before issue joined",
                        "display_name": "[(1, 'No court action (before issue joined)'), (2, 'Order entered'), (11, 'Hearing held'), (12, 'Order decided')]",
                    },
                    {
                        "value": "After issue joined",
                        "display_name": "[(3, 'No court action (after issue joined)'), (4, 'Judgment on motion'), (5, 'Pretrial conference held'), (6, 'During court trial'), (7, 'During jury trial'), (8, 'After court trial'), (9, 'After jury trial'), (10, 'Other'), (13, 'Request for trial de novo after arbitration')]",
                    },
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(in_pre_validator),
    ]
    disposition: Annotated[
        None | str | list[str],
        Field(
            None,
            description="The manner in which the case was disposed of.",
            json_schema_extra={
                "choices": [
                    {
                        "value": "Cases transferred or remanded",
                        "display_name": "[(0, 'Transfer to another district'), (1, 'Remanded to state court'), (10, 'Multi-district litigation transfer'), (11, 'Remanded to U.S. agency')]",
                    },
                    {
                        "value": "Dismissals",
                        "display_name": "[(2, 'Want of prosecution'), (3, 'Lack of jurisdiction'), (12, 'Voluntarily dismissed'), (13, 'Settled'), (14, 'Other')]",
                    },
                    {
                        "value": "Judgment on",
                        "display_name": "[(4, 'Default'), (5, 'Consent'), (6, 'Motion before trial'), (7, 'Jury verdict'), (8, 'Directed verdict'), (9, 'Court trial'), (15, 'Award of arbitrator'), (16, 'Stayed pending bankruptcy'), (17, 'Other'), (18, 'Statistical closing'), (19, 'Appeal affirmed (magistrate judge)'), (20, 'Appeal denied (magistrate judge')]",
                    },
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(in_pre_validator),
    ]
    judgment: Annotated[
        None | int | list[int],
        Field(
            None,
            description="Which party the cases was disposed in favor of.",
            json_schema_extra={
                "choices": [
                    {"value": 1, "display_name": "Plaintiff"},
                    {"value": 2, "display_name": "Defendant"},
                    {
                        "value": 3,
                        "display_name": "Both plaintiff and defendant",
                    },
                    {"value": 4, "display_name": "Unknown"},
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(try_coerce_ints),
        BeforeValidator(in_pre_validator),
    ]
    pro_se: Annotated[
        None | int | list[int],
        Field(
            None,
            description="Which parties filed pro se? (See codebook for more details.)",
            json_schema_extra={
                "choices": [
                    {
                        "value": 0,
                        "display_name": "No pro se plaintiffs or defendants",
                    },
                    {
                        "value": 1,
                        "display_name": "Pro se plaintiffs, but no pro se defendants",
                    },
                    {
                        "value": 2,
                        "display_name": "Pro se defendants, but no pro se plaintiffs",
                    },
                    {
                        "value": 3,
                        "display_name": "Both pro se plaintiffs & defendants",
                    },
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(try_coerce_ints),
        BeforeValidator(in_pre_validator),
    ]
