"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter6, Filter8
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
    related_validator,
)


class GiftsEndpoint(Endpoint):
    """Gifts Endpoint"""

    endpoint: ClassVar[str] = "/gifts/"
    endpoint_id: ClassVar[str] = "gifts"
    endpoint_name: ClassVar[str] = "Gifts"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter which fields are returned.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "source", "display_name": "Source"},
                    {"value": "description", "display_name": "Description"},
                    {"value": "value", "display_name": "Value"},
                    {"value": "redacted", "display_name": "Redacted"},
                    {
                        "value": "financial_disclosure",
                        "display_name": "Financial disclosure",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    source: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Source of the judicial gift. (ex. Alta Ski Area).",
        ),
    ]
    description: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Description of the gift (ex. Season Pass).",
        ),
    ]
    value: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Value of the judicial gift, (ex. $1,199.00)",
        ),
    ]
    redacted: Annotated[
        None | bool,
        Field(
            None,
            description="Does the gift row contain redaction(s)?",
        ),
    ]
    financial_disclosure: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            description="The financial disclosure associated with this gift.",
            json_schema_extra={
                "related_class_name": "FinancialDisclosuresEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
