"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter8
from courtlistener.utils import (
    multiple_choice_validator,
    related_validator,
)


class OpinionsEndpoint(Endpoint):
    """Opinions Endpoint"""

    endpoint: ClassVar[str] = "/opinions/"
    endpoint_id: ClassVar[str] = "opinions"
    endpoint_name: ClassVar[str] = "Opinions"

    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    sha1: Annotated[
        None | str,
        Field(
            None,
            description="unique ID for the document, as generated via SHA1 of the binary file or text data",
        ),
    ]
    extracted_by_ocr: Annotated[
        None | bool,
        Field(
            None,
            description="Whether OCR was used to get this document content",
        ),
    ]
    per_curiam: Annotated[
        None | bool,
        Field(
            None,
            description="Is this opinion per curiam, without a single author?",
        ),
    ]
    cluster: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "ClustersEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    author: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "PeopleEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    joined_by: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "PeopleEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    type: Annotated[
        None | str | list[str],
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "010combined",
                        "display_name": "Combined Opinion",
                    },
                    {
                        "value": "015unamimous",
                        "display_name": "Unanimous Opinion",
                    },
                    {"value": "020lead", "display_name": "Lead Opinion"},
                    {
                        "value": "025plurality",
                        "display_name": "Plurality Opinion",
                    },
                    {
                        "value": "030concurrence",
                        "display_name": "Concurrence Opinion",
                    },
                    {
                        "value": "035concurrenceinpart",
                        "display_name": "In Part Opinion",
                    },
                    {"value": "040dissent", "display_name": "Dissent"},
                    {"value": "050addendum", "display_name": "Addendum"},
                    {"value": "060remittitur", "display_name": "Remittitur"},
                    {"value": "070rehearing", "display_name": "Rehearing"},
                    {
                        "value": "080onthemerits",
                        "display_name": "On the Merits",
                    },
                    {
                        "value": "090onmotiontostrike",
                        "display_name": "On Motion to Strike Cost Bill",
                    },
                    {
                        "value": "100trialcourt",
                        "display_name": "Trial Court Document",
                    },
                ],
            },
        ),
        BeforeValidator(multiple_choice_validator),
    ]
