"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter8
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
    related_validator,
)


class OpinionsEndpoint(Endpoint):
    """Opinions Endpoint"""

    endpoint: ClassVar[str] = "/opinions/"
    endpoint_id: ClassVar[str] = "opinions"
    endpoint_name: ClassVar[str] = "Opinions"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter field returned in the response.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "absolute_url", "display_name": "Absolute url"},
                    {"value": "cluster_id", "display_name": "Cluster id"},
                    {"value": "cluster", "display_name": "Cluster"},
                    {"value": "author_id", "display_name": "Author id"},
                    {"value": "author", "display_name": "Author"},
                    {"value": "joined_by", "display_name": "Joined by"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "author_str", "display_name": "Author str"},
                    {"value": "per_curiam", "display_name": "Per curiam"},
                    {
                        "value": "joined_by_str",
                        "display_name": "Joined by str",
                    },
                    {"value": "type", "display_name": "Type"},
                    {"value": "sha1", "display_name": "Sha1"},
                    {"value": "page_count", "display_name": "Page count"},
                    {"value": "download_url", "display_name": "Download url"},
                    {"value": "local_path", "display_name": "Local path"},
                    {"value": "plain_text", "display_name": "Plain text"},
                    {"value": "html", "display_name": "Html"},
                    {"value": "html_lawbox", "display_name": "Html lawbox"},
                    {
                        "value": "html_columbia",
                        "display_name": "Html columbia",
                    },
                    {
                        "value": "html_anon_2020",
                        "display_name": "Html anon 2020",
                    },
                    {"value": "xml_harvard", "display_name": "Xml harvard"},
                    {
                        "value": "html_with_citations",
                        "display_name": "Html with citations",
                    },
                    {
                        "value": "extracted_by_ocr",
                        "display_name": "Extracted by ocr",
                    },
                    {"value": "ordering_key", "display_name": "Ordering key"},
                    {"value": "main_version", "display_name": "Main version"},
                    {
                        "value": "opinions_cited",
                        "display_name": "Opinions cited",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    sha1: Annotated[
        None | str,
        Field(
            None,
            description="unique ID for the document, as generated via SHA1 of the binary file or text data",
        ),
    ]
    extracted_by_ocr: Annotated[
        None | bool,
        Field(
            None,
            description="Whether OCR was used to get this document content",
        ),
    ]
    per_curiam: Annotated[
        None | bool,
        Field(
            None,
            description="Is this opinion per curiam, without a single author?",
        ),
    ]
    cluster: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "ClustersEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    author: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "PeopleEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    joined_by: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "PeopleEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    type: Annotated[
        None | str | list[str],
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "010combined",
                        "display_name": "Combined Opinion",
                    },
                    {
                        "value": "015unamimous",
                        "display_name": "Unanimous Opinion",
                    },
                    {"value": "020lead", "display_name": "Lead Opinion"},
                    {
                        "value": "025plurality",
                        "display_name": "Plurality Opinion",
                    },
                    {
                        "value": "030concurrence",
                        "display_name": "Concurrence Opinion",
                    },
                    {
                        "value": "035concurrenceinpart",
                        "display_name": "In Part Opinion",
                    },
                    {"value": "040dissent", "display_name": "Dissent"},
                    {"value": "050addendum", "display_name": "Addendum"},
                    {"value": "060remittitur", "display_name": "Remittitur"},
                    {"value": "070rehearing", "display_name": "Rehearing"},
                    {
                        "value": "080onthemerits",
                        "display_name": "On the Merits",
                    },
                    {
                        "value": "090onmotiontostrike",
                        "display_name": "On Motion to Strike Cost Bill",
                    },
                    {
                        "value": "100trialcourt",
                        "display_name": "Trial Court Document",
                    },
                ],
            },
        ),
        BeforeValidator(multiple_choice_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
