"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_models.py` script.
"""

from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter4
from courtlistener.utils import (
    comma_separated_post_validator,
    multiple_choice_validator,
    related_validator,
)


class OpinionsCitedEndpoint(Endpoint):
    """Opinions Cited Endpoint"""

    endpoint: ClassVar[str] = "/opinions-cited/"
    endpoint_id: ClassVar[str] = "opinions-cited"
    endpoint_name: ClassVar[str] = "Opinions Cited"

    fields: Annotated[
        None | str | list[str],
        Field(
            None,
            description="Filter which fields are returned.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {
                        "value": "citing_opinion",
                        "display_name": "Citing opinion",
                    },
                    {
                        "value": "cited_opinion",
                        "display_name": "Cited opinion",
                    },
                    {"value": "depth", "display_name": "Depth"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
    ]
    id: Annotated[
        None | int | Filter4,
        Field(
            None,
        ),
    ]
    citing_opinion: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            description="Related filter: pass a opinions record\u0027s id, or a dict of opinions sub-filters (sent as citing_opinion__\u003csubfilter\u003e lookups). Not an enumerated choice field.",
            json_schema_extra={
                "related_class_name": "OpinionsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    cited_opinion: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            description="Related filter: pass a opinions record\u0027s id, or a dict of opinions sub-filters (sent as cited_opinion__\u003csubfilter\u003e lookups). Not an enumerated choice field.",
            json_schema_extra={
                "related_class_name": "OpinionsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
