"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.utils import (
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class OriginatingCourtInformationEndpoint(Endpoint):
    """Originating Court Information Endpoint"""

    endpoint: ClassVar[str] = "/originating-court-information/"
    endpoint_id: ClassVar[str] = "originating-court-information"
    endpoint_name: ClassVar[str] = "Originating Court Information"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter field returned in the response.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {
                        "value": "docket_number",
                        "display_name": "Docket number",
                    },
                    {
                        "value": "docket_number_raw",
                        "display_name": "Docket number raw",
                    },
                    {
                        "value": "assigned_to_str",
                        "display_name": "Assigned to str",
                    },
                    {
                        "value": "ordering_judge_str",
                        "display_name": "Ordering judge str",
                    },
                    {
                        "value": "court_reporter",
                        "display_name": "Court reporter",
                    },
                    {
                        "value": "date_disposed",
                        "display_name": "Date disposed",
                    },
                    {"value": "date_filed", "display_name": "Date filed"},
                    {
                        "value": "date_judgment",
                        "display_name": "Date judgment",
                    },
                    {
                        "value": "date_judgment_eod",
                        "display_name": "Date judgment eod",
                    },
                    {
                        "value": "date_filed_noa",
                        "display_name": "Date filed noa",
                    },
                    {
                        "value": "date_received_coa",
                        "display_name": "Date received coa",
                    },
                    {
                        "value": "date_rehearing_denied",
                        "display_name": "Date rehearing denied",
                    },
                    {"value": "assigned_to", "display_name": "Assigned to"},
                    {
                        "value": "ordering_judge",
                        "display_name": "Ordering judge",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
