"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.utils import (
    choice_validator,
    in_post_validator,
    in_pre_validator,
    multiple_choice_validator,
    try_coerce_ints,
)


class PrayersEndpoint(Endpoint):
    """Prayers Endpoint"""

    endpoint: ClassVar[str] = "/prayers/"
    endpoint_id: ClassVar[str] = "prayers"
    endpoint_name: ClassVar[str] = "Prayers"

    user: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    recap_document: Annotated[
        None | int,
        Field(
            None,
            description="The document you\u0027re praying for.",
        ),
    ]
    status: Annotated[
        None | int | list[int],
        Field(
            None,
            description="Whether the prayer has been granted or is still waiting.",
            json_schema_extra={
                "choices": [
                    {
                        "value": 1,
                        "display_name": "Still waiting for the document.",
                    },
                    {"value": 2, "display_name": "Prayer has been granted."},
                ],
            },
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(try_coerce_ints),
        BeforeValidator(in_pre_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
