"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter2, Filter8
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    in_post_validator,
    in_pre_validator,
    multiple_choice_validator,
    related_validator,
)


class RecapQueryEndpoint(Endpoint):
    """Recap Query Endpoint"""

    endpoint: ClassVar[str] = "/recap-query/"
    endpoint_id: ClassVar[str] = "recap-query"
    endpoint_name: ClassVar[str] = "Recap Query"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter field returned in the response.",
            json_schema_extra={
                "choices": [
                    {"value": "pacer_doc_id", "display_name": "Pacer doc id"},
                    {
                        "value": "filepath_local",
                        "display_name": "Filepath local",
                    },
                    {
                        "value": "acms_document_guid",
                        "display_name": "Acms document guid",
                    },
                    {"value": "id", "display_name": "ID"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
        ),
    ]
    date_upload: Annotated[
        None | datetime | Filter8,
        Field(
            None,
        ),
    ]
    document_type: Annotated[
        None | int,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": 1, "display_name": "PACER Document"},
                    {"value": 2, "display_name": "Attachment"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    document_number: Annotated[
        None | str | Filter2,
        Field(
            None,
        ),
    ]
    pacer_doc_id: Annotated[
        None | str | list[str],
        Field(
            None,
            description="The ID of the document in PACER.",
        ),
        AfterValidator(in_post_validator),
        BeforeValidator(in_pre_validator),
    ]
    is_available: Annotated[
        None | bool,
        Field(
            None,
        ),
    ]
    sha1: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    ocr_status: Annotated[
        None | int,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": 1, "display_name": "OCR Complete"},
                    {"value": 2, "display_name": "OCR Not Necessary"},
                    {"value": 3, "display_name": "OCR Failed"},
                    {"value": 4, "display_name": "OCR Needed"},
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    is_free_on_pacer: Annotated[
        None | bool,
        Field(
            None,
        ),
    ]
    docket_entry: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "DocketEntriesEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    tags: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            json_schema_extra={
                "related_class_name": "TagsEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
