"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import date
from typing import Annotated, ClassVar, Literal

from pydantic import BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.utils import (
    choice_validator,
    multiple_choice_validator,
    relative_date_validator,
)


class RecapDocumentSearchEndpoint(Endpoint):
    """Recap Document Search Endpoint"""

    endpoint: ClassVar[str] = "/search/"
    endpoint_id: ClassVar[str] = "recap-document-search"
    endpoint_name: ClassVar[str] = "Recap Document Search"

    type: Literal["rd"] = "rd"
    court: Annotated[
        None | str | list[str],
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "scotus",
                        "display_name": "Supreme Court of the United States",
                    },
                    {
                        "value": "ca1",
                        "display_name": "Court of Appeals for the First Circuit",
                    },
                    {
                        "value": "ca2",
                        "display_name": "Court of Appeals for the Second Circuit",
                    },
                    {
                        "value": "ca3",
                        "display_name": "Court of Appeals for the Third Circuit",
                    },
                    {
                        "value": "ca4",
                        "display_name": "Court of Appeals for the Fourth Circuit",
                    },
                    {
                        "value": "ca5",
                        "display_name": "Court of Appeals for the Fifth Circuit",
                    },
                    {
                        "value": "ca6",
                        "display_name": "Court of Appeals for the Sixth Circuit",
                    },
                    {
                        "value": "ca7",
                        "display_name": "Court of Appeals for the Seventh Circuit",
                    },
                    {
                        "value": "ca8",
                        "display_name": "Court of Appeals for the Eighth Circuit",
                    },
                    {
                        "value": "ca9",
                        "display_name": "Court of Appeals for the Ninth Circuit",
                    },
                    {
                        "value": "ca10",
                        "display_name": "Court of Appeals for the Tenth Circuit",
                    },
                    {
                        "value": "ca11",
                        "display_name": "Court of Appeals for the Eleventh Circuit",
                    },
                    {
                        "value": "cadc",
                        "display_name": "Court of Appeals for the D.C. Circuit",
                    },
                    {
                        "value": "cafc",
                        "display_name": "Court of Appeals for the Federal Circuit",
                    },
                    {
                        "value": "dcd",
                        "display_name": "District Court, District of Columbia",
                    },
                    {
                        "value": "almd",
                        "display_name": "District Court, M.D. Alabama",
                    },
                    {
                        "value": "alnd",
                        "display_name": "District Court, N.D. Alabama",
                    },
                    {
                        "value": "alsd",
                        "display_name": "District Court, S.D. Alabama",
                    },
                    {
                        "value": "akd",
                        "display_name": "District Court, D. Alaska",
                    },
                    {
                        "value": "azd",
                        "display_name": "District Court, D. Arizona",
                    },
                    {
                        "value": "ared",
                        "display_name": "District Court, E.D. Arkansas",
                    },
                    {
                        "value": "arwd",
                        "display_name": "District Court, W.D. Arkansas",
                    },
                    {
                        "value": "cacd",
                        "display_name": "District Court, C.D. California",
                    },
                    {
                        "value": "caed",
                        "display_name": "District Court, E.D. California",
                    },
                    {
                        "value": "cand",
                        "display_name": "District Court, N.D. California",
                    },
                    {
                        "value": "casd",
                        "display_name": "District Court, S.D. California",
                    },
                    {
                        "value": "cod",
                        "display_name": "District Court, D. Colorado",
                    },
                    {
                        "value": "ctd",
                        "display_name": "District Court, D. Connecticut",
                    },
                    {
                        "value": "ded",
                        "display_name": "District Court, D. Delaware",
                    },
                    {
                        "value": "flmd",
                        "display_name": "District Court, M.D. Florida",
                    },
                    {
                        "value": "flnd",
                        "display_name": "District Court, N.D. Florida",
                    },
                    {
                        "value": "flsd",
                        "display_name": "District Court, S.D. Florida",
                    },
                    {
                        "value": "gamd",
                        "display_name": "District Court, M.D. Georgia",
                    },
                    {
                        "value": "gand",
                        "display_name": "District Court, N.D. Georgia",
                    },
                    {
                        "value": "gasd",
                        "display_name": "District Court, S.D. Georgia",
                    },
                    {
                        "value": "hid",
                        "display_name": "District Court, D. Hawaii",
                    },
                    {
                        "value": "idd",
                        "display_name": "District Court, D. Idaho",
                    },
                    {
                        "value": "ilcd",
                        "display_name": "District Court, C.D. Illinois",
                    },
                    {
                        "value": "ilnd",
                        "display_name": "District Court, N.D. Illinois",
                    },
                    {
                        "value": "ilsd",
                        "display_name": "District Court, S.D. Illinois",
                    },
                    {
                        "value": "innd",
                        "display_name": "District Court, N.D. Indiana",
                    },
                    {
                        "value": "insd",
                        "display_name": "District Court, S.D. Indiana",
                    },
                    {
                        "value": "iand",
                        "display_name": "District Court, N.D. Iowa",
                    },
                    {
                        "value": "iasd",
                        "display_name": "District Court, S.D. Iowa",
                    },
                    {
                        "value": "ksd",
                        "display_name": "District Court, D. Kansas",
                    },
                    {
                        "value": "kyed",
                        "display_name": "District Court, E.D. Kentucky",
                    },
                    {
                        "value": "kywd",
                        "display_name": "District Court, W.D. Kentucky",
                    },
                    {
                        "value": "laed",
                        "display_name": "District Court, E.D. Louisiana",
                    },
                    {
                        "value": "lamd",
                        "display_name": "District Court, M.D. Louisiana",
                    },
                    {
                        "value": "lawd",
                        "display_name": "District Court, W.D. Louisiana",
                    },
                    {
                        "value": "med",
                        "display_name": "District Court, D. Maine",
                    },
                    {
                        "value": "mdd",
                        "display_name": "District Court, D. Maryland",
                    },
                    {
                        "value": "mad",
                        "display_name": "District Court, D. Massachusetts",
                    },
                    {
                        "value": "mied",
                        "display_name": "District Court, E.D. Michigan",
                    },
                    {
                        "value": "miwd",
                        "display_name": "District Court, W.D. Michigan",
                    },
                    {
                        "value": "mnd",
                        "display_name": "District Court, D. Minnesota",
                    },
                    {
                        "value": "msnd",
                        "display_name": "District Court, N.D. Mississippi",
                    },
                    {
                        "value": "mssd",
                        "display_name": "District Court, S.D. Mississippi",
                    },
                    {
                        "value": "moed",
                        "display_name": "District Court, E.D. Missouri",
                    },
                    {
                        "value": "mowd",
                        "display_name": "District Court, W.D. Missouri",
                    },
                    {
                        "value": "mtd",
                        "display_name": "District Court, D. Montana",
                    },
                    {
                        "value": "ned",
                        "display_name": "District Court, D. Nebraska",
                    },
                    {
                        "value": "nvd",
                        "display_name": "District Court, D. Nevada",
                    },
                    {
                        "value": "nhd",
                        "display_name": "District Court, D. New Hampshire",
                    },
                    {
                        "value": "njd",
                        "display_name": "District Court, D. New Jersey",
                    },
                    {
                        "value": "nmd",
                        "display_name": "District Court, D. New Mexico",
                    },
                    {
                        "value": "nyed",
                        "display_name": "District Court, E.D. New York",
                    },
                    {
                        "value": "nynd",
                        "display_name": "District Court, N.D. New York",
                    },
                    {
                        "value": "nysd",
                        "display_name": "District Court, S.D. New York",
                    },
                    {
                        "value": "nywd",
                        "display_name": "District Court, W.D. New York",
                    },
                    {
                        "value": "nced",
                        "display_name": "District Court, E.D. North Carolina",
                    },
                    {
                        "value": "ncmd",
                        "display_name": "District Court, M.D. North Carolina",
                    },
                    {
                        "value": "ncwd",
                        "display_name": "District Court, W.D. North Carolina",
                    },
                    {
                        "value": "ndd",
                        "display_name": "District Court, D. North Dakota",
                    },
                    {
                        "value": "ohnd",
                        "display_name": "District Court, N.D. Ohio",
                    },
                    {
                        "value": "ohsd",
                        "display_name": "District Court, S.D. Ohio",
                    },
                    {
                        "value": "oked",
                        "display_name": "District Court, E.D. Oklahoma",
                    },
                    {
                        "value": "oknd",
                        "display_name": "District Court, N.D. Oklahoma",
                    },
                    {
                        "value": "okwd",
                        "display_name": "District Court, W.D. Oklahoma",
                    },
                    {
                        "value": "ord",
                        "display_name": "District Court, D. Oregon",
                    },
                    {
                        "value": "paed",
                        "display_name": "District Court, E.D. Pennsylvania",
                    },
                    {
                        "value": "pamd",
                        "display_name": "District Court, M.D. Pennsylvania",
                    },
                    {
                        "value": "pawd",
                        "display_name": "District Court, W.D. Pennsylvania",
                    },
                    {
                        "value": "rid",
                        "display_name": "District Court, D. Rhode Island",
                    },
                    {
                        "value": "scd",
                        "display_name": "District Court, D. South Carolina",
                    },
                    {
                        "value": "sdd",
                        "display_name": "District Court, D. South Dakota",
                    },
                    {
                        "value": "tned",
                        "display_name": "District Court, E.D. Tennessee",
                    },
                    {
                        "value": "tnmd",
                        "display_name": "District Court, M.D. Tennessee",
                    },
                    {
                        "value": "tnwd",
                        "display_name": "District Court, W.D. Tennessee",
                    },
                    {
                        "value": "txed",
                        "display_name": "District Court, E.D. Texas",
                    },
                    {
                        "value": "txnd",
                        "display_name": "District Court, N.D. Texas",
                    },
                    {
                        "value": "txsd",
                        "display_name": "District Court, S.D. Texas",
                    },
                    {
                        "value": "txwd",
                        "display_name": "District Court, W.D. Texas",
                    },
                    {
                        "value": "utd",
                        "display_name": "District Court, D. Utah",
                    },
                    {
                        "value": "vtd",
                        "display_name": "District Court, D. Vermont",
                    },
                    {
                        "value": "vaed",
                        "display_name": "District Court, E.D. Virginia",
                    },
                    {
                        "value": "vawd",
                        "display_name": "District Court, W.D. Virginia",
                    },
                    {
                        "value": "waed",
                        "display_name": "District Court, E.D. Washington",
                    },
                    {
                        "value": "wawd",
                        "display_name": "District Court, W.D. Washington",
                    },
                    {
                        "value": "wvnd",
                        "display_name": "District Court, N.D. West Virginia",
                    },
                    {
                        "value": "wvsd",
                        "display_name": "District Court, S.D. West Virginia",
                    },
                    {
                        "value": "wied",
                        "display_name": "District Court, E.D. Wisconsin",
                    },
                    {
                        "value": "wiwd",
                        "display_name": "District Court, W.D. Wisconsin",
                    },
                    {
                        "value": "wyd",
                        "display_name": "District Court, D. Wyoming",
                    },
                    {
                        "value": "gud",
                        "display_name": "District Court, D. Guam",
                    },
                    {
                        "value": "nmid",
                        "display_name": "District Court, Northern Mariana Islands",
                    },
                    {
                        "value": "prd",
                        "display_name": "District Court, D. Puerto Rico",
                    },
                    {
                        "value": "vid",
                        "display_name": "District Court, Virgin Islands",
                    },
                    {
                        "value": "californiad",
                        "display_name": "District Court, D. California",
                    },
                    {
                        "value": "illinoised",
                        "display_name": "District Court, E.D. Illinois",
                    },
                    {
                        "value": "illinoisd",
                        "display_name": "District Court, D. Illinois",
                    },
                    {
                        "value": "indianad",
                        "display_name": "District Court, D. Indiana",
                    },
                    {
                        "value": "orld",
                        "display_name": "District Court, Orleans",
                    },
                    {
                        "value": "ohiod",
                        "display_name": "District Court, D. Ohio",
                    },
                    {
                        "value": "pennsylvaniad",
                        "display_name": "District Court, D. Pennsylvania",
                    },
                    {
                        "value": "southcarolinaed",
                        "display_name": "District Court, E.D. South Carolina",
                    },
                    {
                        "value": "southcarolinawd",
                        "display_name": "District Court, W.D. South Carolina",
                    },
                    {
                        "value": "tennessed",
                        "display_name": "District Court, D. Tennessee",
                    },
                    {
                        "value": "canalzoned",
                        "display_name": "District Court, Canal Zone",
                    },
                    {
                        "value": "bap1",
                        "display_name": "Bankruptcy Appellate Panel of the First Circuit",
                    },
                    {
                        "value": "bap2",
                        "display_name": "Bankruptcy Appellate Panel of the Second Circuit",
                    },
                    {
                        "value": "bap6",
                        "display_name": "Bankruptcy Appellate Panel of the Sixth Circuit",
                    },
                    {
                        "value": "bap8",
                        "display_name": "United States Bankruptcy Appellate Panel for the Eighth Circuit",
                    },
                    {
                        "value": "bap9",
                        "display_name": "United States Bankruptcy Appellate Panel for the Ninth Circuit",
                    },
                    {
                        "value": "bap10",
                        "display_name": "Bankruptcy Appellate Panel of the Tenth Circuit",
                    },
                    {
                        "value": "bapme",
                        "display_name": "Bankruptcy Appellate Panel, D. Maine",
                    },
                    {
                        "value": "bapma",
                        "display_name": "Bankruptcy Appellate Panel of Massachusetts",
                    },
                    {
                        "value": "almb",
                        "display_name": "United States Bankruptcy Court, M.D. Alabama",
                    },
                    {
                        "value": "alnb",
                        "display_name": "United States Bankruptcy Court, N.D. Alabama",
                    },
                    {
                        "value": "alsb",
                        "display_name": "United States Bankruptcy Court, S.D. Alabama",
                    },
                    {
                        "value": "akb",
                        "display_name": "United States Bankruptcy Court, D. Alaska",
                    },
                    {
                        "value": "arb",
                        "display_name": "United States Bankruptcy Court, D. Arizona",
                    },
                    {
                        "value": "areb",
                        "display_name": "United States Bankruptcy Court, E.D. Arkansas",
                    },
                    {
                        "value": "arwb",
                        "display_name": "United States Bankruptcy Court, W.D. Arkansas",
                    },
                    {
                        "value": "cacb",
                        "display_name": "United States Bankruptcy Court, C.D. California",
                    },
                    {
                        "value": "caeb",
                        "display_name": "United States Bankruptcy Court, E.D. California",
                    },
                    {
                        "value": "canb",
                        "display_name": "United States Bankruptcy Court, N.D. California",
                    },
                    {
                        "value": "casb",
                        "display_name": "United States Bankruptcy Court, S.D. California",
                    },
                    {
                        "value": "cob",
                        "display_name": "United States Bankruptcy Court, D. Colorado",
                    },
                    {
                        "value": "ctb",
                        "display_name": "United States Bankruptcy Court, D. Connecticut",
                    },
                    {
                        "value": "deb",
                        "display_name": "United States Bankruptcy Court, D. Delaware",
                    },
                    {
                        "value": "dcb",
                        "display_name": "United States Bankruptcy Court, District of Columbia",
                    },
                    {
                        "value": "flmb",
                        "display_name": "United States Bankruptcy Court, M.D. Florida",
                    },
                    {
                        "value": "flnb",
                        "display_name": "United States Bankruptcy Court, N.D. Florida",
                    },
                    {
                        "value": "flsb",
                        "display_name": "United States Bankruptcy Court, S.D. Florida.",
                    },
                    {
                        "value": "gamb",
                        "display_name": "United States Bankruptcy Court, M.D. Georgia",
                    },
                    {
                        "value": "ganb",
                        "display_name": "United States Bankruptcy Court, N.D. Georgia",
                    },
                    {
                        "value": "gasb",
                        "display_name": "United States Bankruptcy Court, S.D. Georgia",
                    },
                    {
                        "value": "hib",
                        "display_name": "United States Bankruptcy Court, D. Hawaii",
                    },
                    {
                        "value": "idb",
                        "display_name": "United States Bankruptcy Court, D. Idaho",
                    },
                    {
                        "value": "ilcb",
                        "display_name": "United States Bankruptcy Court, C.D. Illinois",
                    },
                    {
                        "value": "ilnb",
                        "display_name": "United States Bankruptcy Court, N.D. Illinois",
                    },
                    {
                        "value": "ilsb",
                        "display_name": "United States Bankruptcy Court, S.D. Illinois",
                    },
                    {
                        "value": "innb",
                        "display_name": "United States Bankruptcy Court, N.D. Indiana",
                    },
                    {
                        "value": "insb",
                        "display_name": "United States Bankruptcy Court, S.D. Indiana",
                    },
                    {
                        "value": "ianb",
                        "display_name": "United States Bankruptcy Court, N.D. Iowa",
                    },
                    {
                        "value": "iasb",
                        "display_name": "United States Bankruptcy Court, S.D. Iowa",
                    },
                    {
                        "value": "ksb",
                        "display_name": "United States Bankruptcy Court, D. Kansas",
                    },
                    {
                        "value": "kyeb",
                        "display_name": "United States Bankruptcy Court, E.D. Kentucky",
                    },
                    {
                        "value": "kywb",
                        "display_name": "United States Bankruptcy Court, W.D. Kentucky",
                    },
                    {
                        "value": "laeb",
                        "display_name": "United States Bankruptcy Court, E.D. Louisiana",
                    },
                    {
                        "value": "lamb",
                        "display_name": "United States Bankruptcy Court, M.D. Louisiana",
                    },
                    {
                        "value": "lawb",
                        "display_name": "United States Bankruptcy Court, W.D. Louisiana",
                    },
                    {
                        "value": "meb",
                        "display_name": "United States Bankruptcy Court, D. Maine",
                    },
                    {
                        "value": "mdb",
                        "display_name": "United States Bankruptcy Court, D. Maryland",
                    },
                    {
                        "value": "mab",
                        "display_name": "United States Bankruptcy Court, D. Massachusetts",
                    },
                    {
                        "value": "mieb",
                        "display_name": "United States Bankruptcy Court, E.D. Michigan",
                    },
                    {
                        "value": "miwb",
                        "display_name": "United States Bankruptcy Court, W.D. Michigan",
                    },
                    {
                        "value": "mnb",
                        "display_name": "United States Bankruptcy Court, D. Minnesota",
                    },
                    {
                        "value": "msnb",
                        "display_name": "United States Bankruptcy Court, N.D. Mississippi",
                    },
                    {
                        "value": "mssb",
                        "display_name": "United States Bankruptcy Court, S.D. Mississippi",
                    },
                    {
                        "value": "moeb",
                        "display_name": "United States Bankruptcy Court, E.D. Missouri",
                    },
                    {
                        "value": "mowb",
                        "display_name": "United States Bankruptcy Court, W.D. Missouri",
                    },
                    {
                        "value": "mtb",
                        "display_name": "United States Bankruptcy Court, D. Montana",
                    },
                    {
                        "value": "nebraskab",
                        "display_name": "United States Bankruptcy Court, D. Nebraska",
                    },
                    {
                        "value": "nvb",
                        "display_name": "United States Bankruptcy Court, D. Nevada",
                    },
                    {
                        "value": "nhb",
                        "display_name": "United States Bankruptcy Court, D. New Hampshire",
                    },
                    {
                        "value": "njb",
                        "display_name": "United States Bankruptcy Court, D. New Jersey",
                    },
                    {
                        "value": "nmb",
                        "display_name": "United States Bankruptcy Court, D. New Mexico",
                    },
                    {
                        "value": "nyeb",
                        "display_name": "United States Bankruptcy Court, E.D. New York",
                    },
                    {
                        "value": "nynb",
                        "display_name": "United States Bankruptcy Court, N.D. New York",
                    },
                    {
                        "value": "nysb",
                        "display_name": "United States Bankruptcy Court, S.D. New York",
                    },
                    {
                        "value": "nywb",
                        "display_name": "United States Bankruptcy Court, W.D. New York",
                    },
                    {
                        "value": "nceb",
                        "display_name": "United States Bankruptcy Court, E.D. North Carolina",
                    },
                    {
                        "value": "ncmb",
                        "display_name": "United States Bankruptcy Court, M.D. North Carolina",
                    },
                    {
                        "value": "ncwb",
                        "display_name": "United States Bankruptcy Court, W.D. North Carolina",
                    },
                    {
                        "value": "ndb",
                        "display_name": "United States Bankruptcy Court, D. North Dakota",
                    },
                    {
                        "value": "ohnb",
                        "display_name": "United States Bankruptcy Court, N.D. Ohio",
                    },
                    {
                        "value": "ohsb",
                        "display_name": "United States Bankruptcy Court, S.D. Ohio",
                    },
                    {
                        "value": "okeb",
                        "display_name": "United States Bankruptcy Court, E.D. Oklahoma",
                    },
                    {
                        "value": "oknb",
                        "display_name": "United States Bankruptcy Court, N.D. Oklahoma",
                    },
                    {
                        "value": "okwb",
                        "display_name": "United States Bankruptcy Court, W.D. Oklahoma",
                    },
                    {
                        "value": "orb",
                        "display_name": "United States Bankruptcy Court, D. Oregon",
                    },
                    {
                        "value": "paeb",
                        "display_name": "United States Bankruptcy Court, E.D. Pennsylvania",
                    },
                    {
                        "value": "pamb",
                        "display_name": "United States Bankruptcy Court, M.D. Pennsylvania",
                    },
                    {
                        "value": "pawb",
                        "display_name": "United States Bankruptcy Court, W.D. Pennsylvania",
                    },
                    {
                        "value": "rib",
                        "display_name": "United States Bankruptcy Court, D. Rhode Island",
                    },
                    {
                        "value": "scb",
                        "display_name": "United States Bankruptcy Court, D. South Carolina",
                    },
                    {
                        "value": "sdb",
                        "display_name": "United States Bankruptcy Court, D. South Dakota",
                    },
                    {
                        "value": "tneb",
                        "display_name": "United States Bankruptcy Court, E.D. Tennessee",
                    },
                    {
                        "value": "tnmb",
                        "display_name": "United States Bankruptcy Court, M.D. Tennessee",
                    },
                    {
                        "value": "tnwb",
                        "display_name": "United States Bankruptcy Court, W.D. Tennessee",
                    },
                    {
                        "value": "tennesseeb",
                        "display_name": "United States Bankruptcy Court, D. Tennessee",
                    },
                    {
                        "value": "txeb",
                        "display_name": "United States Bankruptcy Court, E.D. Texas",
                    },
                    {
                        "value": "txnb",
                        "display_name": "United States Bankruptcy Court, N.D. Texas",
                    },
                    {
                        "value": "txsb",
                        "display_name": "United States Bankruptcy Court, S.D. Texas",
                    },
                    {
                        "value": "txwb",
                        "display_name": "United States Bankruptcy Court, W.D. Texas",
                    },
                    {
                        "value": "utb",
                        "display_name": "United States Bankruptcy Court, D. Utah",
                    },
                    {
                        "value": "vtb",
                        "display_name": "United States Bankruptcy Court, D. Vermont",
                    },
                    {
                        "value": "vaeb",
                        "display_name": "United States Bankruptcy Court, E.D. Virginia",
                    },
                    {
                        "value": "vawb",
                        "display_name": "United States Bankruptcy Court, W.D. Virginia",
                    },
                    {
                        "value": "waeb",
                        "display_name": "United States Bankruptcy Court, E.D. Washington",
                    },
                    {
                        "value": "wawb",
                        "display_name": "United States Bankruptcy Court, W.D. Washington",
                    },
                    {
                        "value": "wvnb",
                        "display_name": "United States Bankruptcy Court, N.D. West Virginia",
                    },
                    {
                        "value": "wvsb",
                        "display_name": "United States Bankruptcy Court, S.D. West Virginia",
                    },
                    {
                        "value": "wieb",
                        "display_name": "United States Bankruptcy Court, E.D. Wisconsin",
                    },
                    {
                        "value": "wiwb",
                        "display_name": "United States Bankruptcy Court, W.D. Wisconsin",
                    },
                    {
                        "value": "wyb",
                        "display_name": "United States Bankruptcy Court, D. Wyoming",
                    },
                    {
                        "value": "gub",
                        "display_name": "United States Bankruptcy Court, D. Guam",
                    },
                    {
                        "value": "nmib",
                        "display_name": "United States Bankruptcy Court, Northern Mariana Islands",
                    },
                    {
                        "value": "prb",
                        "display_name": "United States Bankruptcy Court, D. Puerto Rico",
                    },
                    {
                        "value": "vib",
                        "display_name": "United States Bankruptcy Court, D. Virgin Islands",
                    },
                    {
                        "value": "ala",
                        "display_name": "Supreme Court of Alabama",
                    },
                    {
                        "value": "alactapp",
                        "display_name": "Alabama Court of Appeals",
                    },
                    {
                        "value": "alacrimapp",
                        "display_name": "Court of Criminal Appeals of Alabama",
                    },
                    {
                        "value": "alacivapp",
                        "display_name": "Court of Civil Appeals of Alabama",
                    },
                    {
                        "value": "alaska",
                        "display_name": "Alaska Supreme Court",
                    },
                    {
                        "value": "alaskactapp",
                        "display_name": "Court of Appeals of Alaska",
                    },
                    {"value": "ariz", "display_name": "Arizona Supreme Court"},
                    {
                        "value": "arizctapp",
                        "display_name": "Court of Appeals of Arizona",
                    },
                    {
                        "value": "ariztaxct",
                        "display_name": "Arizona Tax Court",
                    },
                    {
                        "value": "ark",
                        "display_name": "Supreme Court of Arkansas",
                    },
                    {
                        "value": "arkctapp",
                        "display_name": "Court of Appeals of Arkansas",
                    },
                    {
                        "value": "arkworkcompcom",
                        "display_name": "Arkansas Workers' Compensation Commission",
                    },
                    {
                        "value": "arkag",
                        "display_name": "Arkansas Attorney General Reports",
                    },
                    {
                        "value": "cal",
                        "display_name": "California Supreme Court",
                    },
                    {
                        "value": "calctapp",
                        "display_name": "California Court of Appeal",
                    },
                    {
                        "value": "calappdeptsuper",
                        "display_name": "Appellate Division of the Superior Court of California",
                    },
                    {
                        "value": "calag",
                        "display_name": "California Attorney General Reports",
                    },
                    {
                        "value": "colo",
                        "display_name": "Supreme Court of Colorado",
                    },
                    {
                        "value": "coloctapp",
                        "display_name": "Colorado Court of Appeals",
                    },
                    {
                        "value": "coloworkcompcom",
                        "display_name": "Colorado Industrial Claim Appeals Office",
                    },
                    {
                        "value": "coloag",
                        "display_name": "Colorado Attorney General Reports",
                    },
                    {
                        "value": "conn",
                        "display_name": "Supreme Court of Connecticut",
                    },
                    {
                        "value": "connappct",
                        "display_name": "Connecticut Appellate Court",
                    },
                    {
                        "value": "connsuperct",
                        "display_name": "Connecticut Superior Court",
                    },
                    {
                        "value": "connworkcompcom",
                        "display_name": "Connecticut Compensation Review Board",
                    },
                    {
                        "value": "del",
                        "display_name": "Supreme Court of Delaware",
                    },
                    {
                        "value": "delch",
                        "display_name": "Court of Chancery of Delaware",
                    },
                    {
                        "value": "delorphct",
                        "display_name": "Orphan's Court of Delaware",
                    },
                    {
                        "value": "delsuperct",
                        "display_name": "Superior Court of Delaware",
                    },
                    {
                        "value": "delctcompl",
                        "display_name": "Delaware Court of Common Pleas",
                    },
                    {
                        "value": "delfamct",
                        "display_name": "Delaware Family Court",
                    },
                    {
                        "value": "deljudct",
                        "display_name": "Court on the Judiciary of Delaware.",
                    },
                    {
                        "value": "dc",
                        "display_name": "District of Columbia Court of Appeals",
                    },
                    {
                        "value": "fla",
                        "display_name": "Supreme Court of Florida",
                    },
                    {
                        "value": "fladistctapp",
                        "display_name": "District Court of Appeal of Florida",
                    },
                    {
                        "value": "flaag",
                        "display_name": "Florida Attorney General Reports",
                    },
                    {
                        "value": "ga",
                        "display_name": "Supreme Court of Georgia",
                    },
                    {
                        "value": "gactapp",
                        "display_name": "Court of Appeals of Georgia",
                    },
                    {"value": "haw", "display_name": "Hawaii Supreme Court"},
                    {
                        "value": "hawapp",
                        "display_name": "Hawaii Intermediate Court of Appeals",
                    },
                    {"value": "idaho", "display_name": "Idaho Supreme Court"},
                    {
                        "value": "idahoctapp",
                        "display_name": "Idaho Court of Appeals",
                    },
                    {"value": "ill", "display_name": "Illinois Supreme Court"},
                    {
                        "value": "illappct",
                        "display_name": "Appellate Court of Illinois",
                    },
                    {"value": "ind", "display_name": "Indiana Supreme Court"},
                    {
                        "value": "indctapp",
                        "display_name": "Indiana Court of Appeals",
                    },
                    {"value": "indtc", "display_name": "Indiana Tax Court"},
                    {"value": "iowa", "display_name": "Supreme Court of Iowa"},
                    {
                        "value": "iowactapp",
                        "display_name": "Court of Appeals of Iowa",
                    },
                    {
                        "value": "kan",
                        "display_name": "Supreme Court of Kansas",
                    },
                    {
                        "value": "kanctapp",
                        "display_name": "Court of Appeals of Kansas",
                    },
                    {
                        "value": "kanag",
                        "display_name": "Kansas Attorney General Reports",
                    },
                    {"value": "ky", "display_name": "Kentucky Supreme Court"},
                    {
                        "value": "kyctapp",
                        "display_name": "Court of Appeals of Kentucky",
                    },
                    {
                        "value": "kyctapphigh",
                        "display_name": "Court of Appeals of Kentucky (pre-1976)",
                    },
                    {
                        "value": "la",
                        "display_name": "Supreme Court of Louisiana",
                    },
                    {
                        "value": "lactapp",
                        "display_name": "Louisiana Court of Appeal",
                    },
                    {
                        "value": "laag",
                        "display_name": "Louisiana Attorney General Reports",
                    },
                    {
                        "value": "me",
                        "display_name": "Supreme Judicial Court of Maine",
                    },
                    {
                        "value": "mesuperct",
                        "display_name": "Superior Court of Maine",
                    },
                    {
                        "value": "md",
                        "display_name": "Court of Appeals of Maryland",
                    },
                    {
                        "value": "mdctspecapp",
                        "display_name": "Court of Special Appeals of Maryland",
                    },
                    {
                        "value": "mdch",
                        "display_name": "High Court of Chancery of Maryland",
                    },
                    {
                        "value": "mdag",
                        "display_name": "Maryland Attorney General Reports",
                    },
                    {
                        "value": "mass",
                        "display_name": "Massachusetts Supreme Judicial Court",
                    },
                    {
                        "value": "massappct",
                        "display_name": "Massachusetts Appeals Court",
                    },
                    {
                        "value": "masssuperct",
                        "display_name": "Massachusetts Superior Court",
                    },
                    {
                        "value": "massdistct",
                        "display_name": "Massachusetts District Court",
                    },
                    {
                        "value": "masslandct",
                        "display_name": "Massachusetts Land Court",
                    },
                    {
                        "value": "maworkcompcom",
                        "display_name": "Massachusetts Department of Industrial Accidents",
                    },
                    {
                        "value": "mich",
                        "display_name": "Michigan Supreme Court",
                    },
                    {
                        "value": "michctapp",
                        "display_name": "Michigan Court of Appeals",
                    },
                    {
                        "value": "minn",
                        "display_name": "Supreme Court of Minnesota",
                    },
                    {
                        "value": "minnctapp",
                        "display_name": "Court of Appeals of Minnesota",
                    },
                    {
                        "value": "minnag",
                        "display_name": "Minnesota Attorney General Reports",
                    },
                    {
                        "value": "miss",
                        "display_name": "Mississippi Supreme Court",
                    },
                    {
                        "value": "missctapp",
                        "display_name": "Court of Appeals of Mississippi",
                    },
                    {
                        "value": "mo",
                        "display_name": "Supreme Court of Missouri",
                    },
                    {
                        "value": "moctapp",
                        "display_name": "Missouri Court of Appeals",
                    },
                    {
                        "value": "moag",
                        "display_name": "Missouri Attorney General Reports",
                    },
                    {"value": "mont", "display_name": "Montana Supreme Court"},
                    {
                        "value": "monttc",
                        "display_name": "Montana Tax Appeal Board",
                    },
                    {
                        "value": "montag",
                        "display_name": "Montana Attorney General Reports",
                    },
                    {"value": "neb", "display_name": "Nebraska Supreme Court"},
                    {
                        "value": "nebctapp",
                        "display_name": "Nebraska Court of Appeals",
                    },
                    {
                        "value": "nebag",
                        "display_name": "Nebraska Attorney General Reports",
                    },
                    {"value": "nev", "display_name": "Nevada Supreme Court"},
                    {
                        "value": "nevapp",
                        "display_name": "Court of Appeals of Nevada",
                    },
                    {
                        "value": "nh",
                        "display_name": "Supreme Court of New Hampshire",
                    },
                    {
                        "value": "nj",
                        "display_name": "Supreme Court of New Jersey",
                    },
                    {
                        "value": "njsuperctappdiv",
                        "display_name": "New Jersey Superior Court Appellate Division",
                    },
                    {
                        "value": "njtaxct",
                        "display_name": "New Jersey Tax Court",
                    },
                    {
                        "value": "njch",
                        "display_name": "New Jersey Court of Chancery",
                    },
                    {
                        "value": "nm",
                        "display_name": "New Mexico Supreme Court",
                    },
                    {
                        "value": "nmctapp",
                        "display_name": "New Mexico Court of Appeals",
                    },
                    {
                        "value": "ny",
                        "display_name": "New York Court of Appeals",
                    },
                    {
                        "value": "nyappdiv",
                        "display_name": "Appellate Division of the Supreme Court of the State of New York",
                    },
                    {
                        "value": "nyappterm",
                        "display_name": "Appellate Terms of the Supreme Court of New York",
                    },
                    {
                        "value": "nysupct",
                        "display_name": "New York Supreme Court",
                    },
                    {
                        "value": "nycountyct",
                        "display_name": "New York County Courts",
                    },
                    {
                        "value": "nydistct",
                        "display_name": "New York District Court",
                    },
                    {
                        "value": "nyjustct",
                        "display_name": "New York Justice Court",
                    },
                    {
                        "value": "nyfamct",
                        "display_name": "New York Family Court",
                    },
                    {
                        "value": "nysurct",
                        "display_name": "New York Surrogate's Court",
                    },
                    {
                        "value": "nycivct",
                        "display_name": "Civil Court of the City of New York",
                    },
                    {
                        "value": "nycrimct",
                        "display_name": "Criminal Court of the City of New York",
                    },
                    {
                        "value": "nyag",
                        "display_name": "New York Attorney General Reports",
                    },
                    {
                        "value": "nc",
                        "display_name": "Supreme Court of North Carolina",
                    },
                    {
                        "value": "ncctapp",
                        "display_name": "Court of Appeals of North Carolina",
                    },
                    {
                        "value": "ncsuperct",
                        "display_name": "Superior Court of North Carolina",
                    },
                    {
                        "value": "ncbizct",
                        "display_name": "North Carolina Business Court",
                    },
                    {
                        "value": "ncworkcompcom",
                        "display_name": "North Carolina Industrial Commission",
                    },
                    {
                        "value": "nd",
                        "display_name": "North Dakota Supreme Court",
                    },
                    {
                        "value": "ndctapp",
                        "display_name": "North Dakota Court of Appeals",
                    },
                    {"value": "ohio", "display_name": "Ohio Supreme Court"},
                    {
                        "value": "ohioctapp",
                        "display_name": "Ohio Court of Appeals",
                    },
                    {
                        "value": "ohioctcl",
                        "display_name": "Ohio Court of Claims",
                    },
                    {
                        "value": "okla",
                        "display_name": "Supreme Court of Oklahoma",
                    },
                    {
                        "value": "oklacivapp",
                        "display_name": "Court of Civil Appeals of Oklahoma",
                    },
                    {
                        "value": "oklacrimapp",
                        "display_name": "Court of Criminal Appeals of Oklahoma",
                    },
                    {
                        "value": "oklajeap",
                        "display_name": "Oklahoma Judicial Ethics Advisory Panel",
                    },
                    {
                        "value": "oklacoj",
                        "display_name": "Court on the Judiciary of Oklahoma",
                    },
                    {
                        "value": "oklaag",
                        "display_name": "Oklahoma Attorney General Reports",
                    },
                    {"value": "or", "display_name": "Oregon Supreme Court"},
                    {
                        "value": "orctapp",
                        "display_name": "Court of Appeals of Oregon",
                    },
                    {"value": "ortc", "display_name": "Oregon Tax Court"},
                    {
                        "value": "pa",
                        "display_name": "Supreme Court of Pennsylvania",
                    },
                    {
                        "value": "pasuperct",
                        "display_name": "Superior Court of Pennsylvania",
                    },
                    {
                        "value": "pacommwct",
                        "display_name": "Commonwealth Court of Pennsylvania",
                    },
                    {
                        "value": "cjdpa",
                        "display_name": "Court of Judicial Discipline of Pennsylvania",
                    },
                    {
                        "value": "ri",
                        "display_name": "Supreme Court of Rhode Island",
                    },
                    {
                        "value": "risuperct",
                        "display_name": "Superior Court of Rhode Island",
                    },
                    {
                        "value": "sc",
                        "display_name": "Supreme Court of South Carolina",
                    },
                    {
                        "value": "scctapp",
                        "display_name": "Court of Appeals of South Carolina",
                    },
                    {
                        "value": "sd",
                        "display_name": "South Dakota Supreme Court",
                    },
                    {
                        "value": "tenn",
                        "display_name": "Tennessee Supreme Court",
                    },
                    {
                        "value": "tennctapp",
                        "display_name": "Court of Appeals of Tennessee",
                    },
                    {
                        "value": "tenncrimapp",
                        "display_name": "Court of Criminal Appeals of Tennessee",
                    },
                    {
                        "value": "tennworkcompcl",
                        "display_name": "Tennessee Court of Workers' Compensation Claims",
                    },
                    {
                        "value": "tennworkcompapp",
                        "display_name": "Tennessee Workers' Compensation Appeals Board",
                    },
                    {
                        "value": "tennsuperct",
                        "display_name": "Tennessee Superior Court for Law and Equity",
                    },
                    {"value": "tex", "display_name": "Texas Supreme Court"},
                    {
                        "value": "texapp",
                        "display_name": "Court of Appeals of Texas",
                    },
                    {
                        "value": "texcrimapp",
                        "display_name": "Court of Criminal Appeals of Texas",
                    },
                    {
                        "value": "texreview",
                        "display_name": "Texas Special Court of Review",
                    },
                    {
                        "value": "texjpml",
                        "display_name": "Texas Judicial Panel on Multidistrict Litigation",
                    },
                    {
                        "value": "texag",
                        "display_name": "Texas Attorney General Reports",
                    },
                    {
                        "value": "texbizct",
                        "display_name": "Texas Business Court",
                    },
                    {"value": "utah", "display_name": "Utah Supreme Court"},
                    {
                        "value": "utahctapp",
                        "display_name": "Court of Appeals of Utah",
                    },
                    {
                        "value": "vt",
                        "display_name": "Supreme Court of Vermont",
                    },
                    {
                        "value": "vtsuperct",
                        "display_name": "Vermont Superior Court",
                    },
                    {
                        "value": "va",
                        "display_name": "Supreme Court of Virginia",
                    },
                    {
                        "value": "vactapp",
                        "display_name": "Court of Appeals of Virginia",
                    },
                    {
                        "value": "wash",
                        "display_name": "Washington Supreme Court",
                    },
                    {
                        "value": "washctapp",
                        "display_name": "Court of Appeals of Washington",
                    },
                    {
                        "value": "washag",
                        "display_name": "Washington Attorney General Reports",
                    },
                    {
                        "value": "washterr",
                        "display_name": "Washington Territory",
                    },
                    {
                        "value": "wva",
                        "display_name": "West Virginia Supreme Court",
                    },
                    {
                        "value": "wvactapp",
                        "display_name": "Intermediate Court of Appeals of West Virginia",
                    },
                    {
                        "value": "wis",
                        "display_name": "Wisconsin Supreme Court",
                    },
                    {
                        "value": "wisctapp",
                        "display_name": "Court of Appeals of Wisconsin",
                    },
                    {
                        "value": "wisag",
                        "display_name": "Wisconsin Attorney General Reports",
                    },
                    {"value": "wyo", "display_name": "Wyoming Supreme Court"},
                    {"value": "guam", "display_name": "Supreme Court of Guam"},
                    {
                        "value": "nmariana",
                        "display_name": "Supreme Court of The Commonwealth of The Northern Mariana Islands",
                    },
                    {
                        "value": "cnmisuperct",
                        "display_name": "Northern Mariana Islands Commonwealth Superior Court",
                    },
                    {
                        "value": "cnmitrialct",
                        "display_name": "Northern Mariana Islands Commonwealth Trial Court",
                    },
                    {
                        "value": "prsupreme",
                        "display_name": "Supreme Court of Puerto Rico",
                    },
                    {
                        "value": "prapp",
                        "display_name": "Tribunal De Apelaciones De Puerto Rico/Court of Appeals of Puerto Rico",
                    },
                    {
                        "value": "virginislands",
                        "display_name": "Supreme Court of The Virgin Islands",
                    },
                    {
                        "value": "amsamoa",
                        "display_name": "High Court of American Samoa",
                    },
                    {
                        "value": "amsamoatc",
                        "display_name": "American Samoa District Court",
                    },
                    {
                        "value": "afcca",
                        "display_name": "United States Air Force Court of Criminal Appeals",
                    },
                    {
                        "value": "usafctmilrev",
                        "display_name": "U S Air Force Court of Military Review",
                    },
                    {
                        "value": "armfor",
                        "display_name": "Court of Appeals for the Armed Forces",
                    },
                    {
                        "value": "cma",
                        "display_name": "United States Court of Military Appeals",
                    },
                    {
                        "value": "acca",
                        "display_name": "Army Court of Criminal Appeals",
                    },
                    {
                        "value": "usarmymilrev",
                        "display_name": "U.S. Army Court of Military Review",
                    },
                    {
                        "value": "uscgcoca",
                        "display_name": "U S Coast Guard Court of Criminal Appeals",
                    },
                    {
                        "value": "cgcomilrev",
                        "display_name": "U S Coast Guard Court of Military Review",
                    },
                    {
                        "value": "mc",
                        "display_name": "United States Court of Military Commission Review",
                    },
                    {
                        "value": "nmcca",
                        "display_name": "Navy-Marine Corps Court of Criminal Appeals",
                    },
                    {
                        "value": "usnmcmilrev",
                        "display_name": "U.S. Navy-Marine Corps Court of Military Review",
                    },
                    {
                        "value": "cherokee",
                        "display_name": "Cherokee Nation Supreme Court",
                    },
                    {
                        "value": "cherokeeapp",
                        "display_name": "Cherokee Nation Judicial Appeals Tribunal",
                    },
                    {
                        "value": "cherokeetribct",
                        "display_name": "Cherokee Indian Tribal Court",
                    },
                    {
                        "value": "cheyrsiouxctapp",
                        "display_name": "Cheyenne River Sioux Tribal Court of Appeals",
                    },
                    {
                        "value": "colvctapp",
                        "display_name": "Colville Confederated Court of Appeals",
                    },
                    {
                        "value": "coquct",
                        "display_name": "Coquille Indian Tribal Court",
                    },
                    {
                        "value": "echerkokee",
                        "display_name": "Eastern Band of Cherokee Indians Supreme Court",
                    },
                    {
                        "value": "echerokeect",
                        "display_name": "Eastern Band of Cherokee Indians Tribal Court",
                    },
                    {
                        "value": "ftmcdowctapp",
                        "display_name": "Fort McDowell Yavapai Nation Tribal Court of Appeals",
                    },
                    {
                        "value": "ftmcdowell",
                        "display_name": "Fort McDowell Supreme Court",
                    },
                    {
                        "value": "ftpeckctapp",
                        "display_name": "Fort Peck Appellate Court",
                    },
                    {
                        "value": "ftpecktrialct",
                        "display_name": "Fort Peck Tribal Court",
                    },
                    {
                        "value": "grrondectapp",
                        "display_name": "Grand Ronde Court of Appeals",
                    },
                    {
                        "value": "grrondect",
                        "display_name": "Grand Ronde Tribal Court",
                    },
                    {
                        "value": "grtravbandctapp",
                        "display_name": "Grand Traverse Band of Ottawa & Chippewa Indians Tribal Appellate Court",
                    },
                    {
                        "value": "grtravbandct",
                        "display_name": "Grand Traverse Band of Ottawa and Chippewa Indians Tribal Court",
                    },
                    {
                        "value": "hochunk",
                        "display_name": "Ho-Chunk Nation Supreme Court",
                    },
                    {
                        "value": "hochunkct",
                        "display_name": "Ho-Chunk Nation Trial Court",
                    },
                    {
                        "value": "hopiappct",
                        "display_name": "Hopi Appellate Court",
                    },
                    {
                        "value": "leechojibtr",
                        "display_name": "Leech Lake Band of Ojibwe Tribal Court",
                    },
                    {
                        "value": "lrbottawactapp",
                        "display_name": "Little River Band of Ottawa Indians Tribal Court of Appeals",
                    },
                    {
                        "value": "lrbottawact",
                        "display_name": "Little River Band of Ottawa Indians Tribal Court",
                    },
                    {
                        "value": "odawactapp",
                        "display_name": "Little Traverse Bay Bands of Odawa Indians Tribal Appellate Court",
                    },
                    {
                        "value": "moheganctapp",
                        "display_name": "Mohegan Tribal Court of Appeals",
                    },
                    {
                        "value": "moheganct",
                        "display_name": "Mohegan Trial Court",
                    },
                    {
                        "value": "mohegangct",
                        "display_name": "Mohegan Gaming Disputes Trial Court",
                    },
                    {
                        "value": "mohegangctapp",
                        "display_name": "Mohegan Gaming Disputes Court of Appeals",
                    },
                    {
                        "value": "moheganelders",
                        "display_name": "Council of Elders of the Mohegan Tribe",
                    },
                    {
                        "value": "navajo",
                        "display_name": "Navajo Nation Supreme Court",
                    },
                    {
                        "value": "navajoctapp",
                        "display_name": "Navajo Nation Court of Appeals",
                    },
                    {
                        "value": "navajofamct",
                        "display_name": "Navajo Nation Family Court",
                    },
                    {
                        "value": "navajochildct",
                        "display_name": "Navajo Nation Children's Court",
                    },
                    {
                        "value": "oneidactapp",
                        "display_name": "Oneida Appellate Court",
                    },
                    {
                        "value": "oneidatrialct",
                        "display_name": "Oneida Tribal Judicial System, Trial Court",
                    },
                    {
                        "value": "sacfoxsupct",
                        "display_name": "Sac and Fox Nation Supreme Court",
                    },
                    {
                        "value": "sacfoxdistct",
                        "display_name": "Sac and Fox Nation District Court",
                    },
                    {
                        "value": "salishctapp",
                        "display_name": "Confederated Salish & Kootenai Court of Appeals",
                    },
                    {
                        "value": "shoaraphotr",
                        "display_name": "Shoshone and Arapaho Tribal Court",
                    },
                    {
                        "value": "swinomishappct",
                        "display_name": "Swinomish Tribal Court of Appeals",
                    },
                    {
                        "value": "swinomishtr",
                        "display_name": "Swinomish Tribal Court",
                    },
                    {
                        "value": "tulalipctapp",
                        "display_name": "Tulalip Court of Appeals",
                    },
                    {
                        "value": "webchippewatr",
                        "display_name": "White Earth Band of Chippewa Tribal Court",
                    },
                    {
                        "value": "asbca",
                        "display_name": "Armed Services Board of Contract Appeals",
                    },
                    {
                        "value": "uscfc",
                        "display_name": "United States Court of Federal Claims",
                    },
                    {
                        "value": "tax",
                        "display_name": "United States Tax Court",
                    },
                    {
                        "value": "bia",
                        "display_name": "Board of Immigration Appeals",
                    },
                    {
                        "value": "olc",
                        "display_name": "Department of Justice Office of Legal Counsel",
                    },
                    {
                        "value": "mspb",
                        "display_name": "Merit Systems Protection Board",
                    },
                    {
                        "value": "cavc",
                        "display_name": "United States Court of Appeals for Veterans Claims",
                    },
                    {
                        "value": "bva",
                        "display_name": "Board of Veterans' Appeals",
                    },
                    {
                        "value": "fiscr",
                        "display_name": "Foreign Intelligence Surveillance Court of Review",
                    },
                    {
                        "value": "fisc",
                        "display_name": "Foreign Intelligence Surveillance Court",
                    },
                    {
                        "value": "cit",
                        "display_name": "United States Court of International Trade",
                    },
                    {
                        "value": "usjc",
                        "display_name": "United States Judicial Conference Committee",
                    },
                    {
                        "value": "jpml",
                        "display_name": "United States Judicial Panel on Multidistrict Litigation",
                    },
                    {
                        "value": "cc",
                        "display_name": "United States Court of Claims",
                    },
                    {"value": "com", "display_name": "Commerce Court"},
                    {
                        "value": "ccpa",
                        "display_name": "Court of Customs and Patent Appeals",
                    },
                    {
                        "value": "cusc",
                        "display_name": "United States Customs Court",
                    },
                    {
                        "value": "bta",
                        "display_name": "United States Board of Tax Appeals",
                    },
                    {
                        "value": "eca",
                        "display_name": "Emergency Court of Appeals",
                    },
                    {
                        "value": "tecoa",
                        "display_name": "Temporary Emergency Court of Appeals",
                    },
                    {
                        "value": "reglrailreorgct",
                        "display_name": "Special Court under the Regional Rail Reorganization Act",
                    },
                    {
                        "value": "kingsbench",
                        "display_name": "Court of King's Bench",
                    },
                ],
            },
        ),
        BeforeValidator(multiple_choice_validator),
    ]
    q: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    available_only: Annotated[
        None | bool,
        Field(
            None,
        ),
    ]
    case_name: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    description: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    docket_number: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    nature_of_suit: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    cause: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    filed_before: Annotated[
        None | str | date,
        Field(
            None,
        ),
        BeforeValidator(relative_date_validator),
    ]
    filed_after: Annotated[
        None | str | date,
        Field(
            None,
        ),
        BeforeValidator(relative_date_validator),
    ]
    entry_date_filed_before: Annotated[
        None | str | date,
        Field(
            None,
        ),
        BeforeValidator(relative_date_validator),
    ]
    entry_date_filed_after: Annotated[
        None | str | date,
        Field(
            None,
        ),
        BeforeValidator(relative_date_validator),
    ]
    document_number: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    attachment_number: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    assigned_to: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    referred_to: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    party_name: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    atty_name: Annotated[
        None | str,
        Field(
            None,
        ),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "score desc", "display_name": "Relevance"},
                    {
                        "value": "dateFiled desc",
                        "display_name": "Newest Cases First",
                    },
                    {
                        "value": "dateFiled asc",
                        "display_name": "Oldest Cases First",
                    },
                    {
                        "value": "entry_date_filed desc",
                        "display_name": "Newest Documents First",
                    },
                    {
                        "value": "entry_date_filed asc",
                        "display_name": "Oldest Documents First",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
