"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter6, Filter8
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
    related_validator,
)


class ReimbursementsEndpoint(Endpoint):
    """Reimbursements Endpoint"""

    endpoint: ClassVar[str] = "/reimbursements/"
    endpoint_id: ClassVar[str] = "reimbursements"
    endpoint_name: ClassVar[str] = "Reimbursements"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "source", "display_name": "Source"},
                    {"value": "date_raw", "display_name": "Date raw"},
                    {"value": "location", "display_name": "Location"},
                    {"value": "purpose", "display_name": "Purpose"},
                    {
                        "value": "items_paid_or_provided",
                        "display_name": "Items paid or provided",
                    },
                    {"value": "redacted", "display_name": "Redacted"},
                    {
                        "value": "financial_disclosure",
                        "display_name": "Financial disclosure",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    redacted: Annotated[
        None | bool,
        Field(
            None,
            description="Does the reimbursement contain redaction(s)?",
        ),
    ]
    date_raw: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Dates as a text string for the date of reimbursements. This is often conference dates (ex. June 2-6, 2011).",
        ),
    ]
    location: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Location of the reimbursement (ex. Harvard Law School, Cambridge, MA).",
        ),
    ]
    source: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Source of the reimbursement (ex. FSU Law School).",
        ),
    ]
    purpose: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Purpose of the reimbursement (ex. Baseball announcer).",
        ),
    ]
    items_paid_or_provided: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Items reimbursed (ex. Room, Airfare).",
        ),
    ]
    financial_disclosure: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            description="The financial disclosure associated with this reimbursement.",
            json_schema_extra={
                "related_class_name": "FinancialDisclosuresEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
