"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import date, datetime
from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter7, Filter8
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class RetentionEventsEndpoint(Endpoint):
    """Retention Events Endpoint"""

    endpoint: ClassVar[str] = "/retention-events/"
    endpoint_id: ClassVar[str] = "retention-events"
    endpoint_name: ClassVar[str] = "Retention Events"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter which fields are returned.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "position", "display_name": "Position"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {
                        "value": "retention_type",
                        "display_name": "Retention type",
                    },
                    {
                        "value": "date_retention",
                        "display_name": "Date retention",
                    },
                    {"value": "votes_yes", "display_name": "Votes yes"},
                    {"value": "votes_no", "display_name": "Votes no"},
                    {
                        "value": "votes_yes_percent",
                        "display_name": "Votes yes percent",
                    },
                    {
                        "value": "votes_no_percent",
                        "display_name": "Votes no percent",
                    },
                    {"value": "unopposed", "display_name": "Unopposed"},
                    {"value": "won", "display_name": "Won"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    position: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    date_retention: Annotated[
        None | date | Filter7,
        Field(
            None,
            description="The date of retention",
        ),
    ]
    retention_type: Annotated[
        None | str,
        Field(
            None,
            description="The method through which this position was retained.",
            json_schema_extra={
                "choices": [
                    {
                        "value": "reapp_gov",
                        "display_name": "Governor Reappointment",
                    },
                    {
                        "value": "reapp_leg",
                        "display_name": "Legislative Reappointment",
                    },
                    {"value": "elec_p", "display_name": "Partisan Election"},
                    {
                        "value": "elec_n",
                        "display_name": "Nonpartisan Election",
                    },
                    {
                        "value": "elec_u",
                        "display_name": "Uncontested Election",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
    votes_yes: Annotated[
        None | int,
        Field(
            None,
            description="If votes are an integer, this is the number of votes in favor of a position.",
        ),
    ]
    votes_no: Annotated[
        None | int,
        Field(
            None,
            description="If votes are an integer, this is the number of votes opposed to a position.",
        ),
    ]
    unopposed: Annotated[
        None | bool,
        Field(
            None,
            description="Whether the position was unopposed at the time of retention.",
        ),
    ]
    won: Annotated[
        None | bool,
        Field(
            None,
            description="Whether the retention event was won.",
        ),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {
                        "value": "date_retention",
                        "display_name": "Date Retention (asc)",
                    },
                    {
                        "value": "-date_retention",
                        "display_name": "Date Retention (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
