"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, ClassVar

from pydantic import BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter8
from courtlistener.utils import (
    choice_validator,
)


class SourcesEndpoint(Endpoint):
    """Sources Endpoint"""

    endpoint: ClassVar[str] = "/sources/"
    endpoint_id: ClassVar[str] = "sources"
    endpoint_name: ClassVar[str] = "Sources"

    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    person: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "Id (asc)"},
                    {"value": "-id", "display_name": "Id (desc)"},
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {
                        "value": "date_accessed",
                        "display_name": "Date Accessed (asc)",
                    },
                    {
                        "value": "-date_accessed",
                        "display_name": "Date Accessed (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
