"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from datetime import datetime
from typing import Annotated, Any, ClassVar

from pydantic import BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter6, Filter8
from courtlistener.utils import (
    related_validator,
)


class SpouseIncomesEndpoint(Endpoint):
    """Spouse Incomes Endpoint"""

    endpoint: ClassVar[str] = "/spouse-incomes/"
    endpoint_id: ClassVar[str] = "spouse-incomes"
    endpoint_name: ClassVar[str] = "Spouse Incomes"

    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    date_created: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The moment when the item was created.",
        ),
    ]
    date_modified: Annotated[
        None | datetime | Filter8,
        Field(
            None,
            description="The last moment when the item was modified. A value in year 1750 indicates the value is unknown",
        ),
    ]
    redacted: Annotated[
        None | bool,
        Field(
            None,
            description="Does the spousal-income row contain redaction(s)?",
        ),
    ]
    date_raw: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Date of spousal income (ex. 2011).",
        ),
    ]
    source_type: Annotated[
        None | str | Filter6,
        Field(
            None,
            description="Source and type of income of judicial spouse (ex. Salary from Bank job).",
        ),
    ]
    financial_disclosure: Annotated[
        None | dict[str, Any] | int,
        Field(
            None,
            description="The financial disclosure associated with this spouse income.",
            json_schema_extra={
                "related_class_name": "FinancialDisclosuresEndpoint",
            },
        ),
        BeforeValidator(related_validator),
    ]
