"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter4


class TagsEndpoint(Endpoint):
    """Tags Endpoint"""

    endpoint: ClassVar[str] = "/tags/"
    endpoint_id: ClassVar[str] = "tags"
    endpoint_name: ClassVar[str] = "Tags"

    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    user: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    name: Annotated[
        None | str | Filter4,
        Field(
            None,
            description="The name of the tag",
        ),
    ]
    published: Annotated[
        None | bool,
        Field(
            None,
            description="Whether the tag has been shared publicly.",
        ),
    ]
