"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.models.filters import Filter4
from courtlistener.utils import (
    choice_validator,
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class TagsEndpoint(Endpoint):
    """Tags Endpoint"""

    endpoint: ClassVar[str] = "/tags/"
    endpoint_id: ClassVar[str] = "tags"
    endpoint_name: ClassVar[str] = "Tags"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {"value": "id", "display_name": "ID"},
                    {"value": "description", "display_name": "Description"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "name", "display_name": "Name"},
                    {"value": "title", "display_name": "Title"},
                    {"value": "view_count", "display_name": "View count"},
                    {"value": "published", "display_name": "Published"},
                    {"value": "dockets", "display_name": "Dockets"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
    id: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    user: Annotated[
        None | int,
        Field(
            None,
        ),
    ]
    name: Annotated[
        None | str | Filter4,
        Field(
            None,
            description="The name of the tag",
        ),
    ]
    published: Annotated[
        None | bool,
        Field(
            None,
            description="Whether the tag has been shared publicly.",
        ),
    ]
    order_by: Annotated[
        None | str,
        Field(
            None,
            json_schema_extra={
                "choices": [
                    {
                        "value": "date_created",
                        "display_name": "Date Created (asc)",
                    },
                    {
                        "value": "-date_created",
                        "display_name": "Date Created (desc)",
                    },
                    {
                        "value": "date_modified",
                        "display_name": "Date Modified (asc)",
                    },
                    {
                        "value": "-date_modified",
                        "display_name": "Date Modified (desc)",
                    },
                    {"value": "name", "display_name": "Name (asc)"},
                    {"value": "-name", "display_name": "Name (desc)"},
                    {
                        "value": "view_count",
                        "display_name": "View Count (asc)",
                    },
                    {
                        "value": "-view_count",
                        "display_name": "View Count (desc)",
                    },
                ],
            },
        ),
        BeforeValidator(choice_validator),
    ]
