"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.utils import (
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class VisualizationsEndpoint(Endpoint):
    """Visualizations Endpoint"""

    endpoint: ClassVar[str] = "/visualizations/"
    endpoint_id: ClassVar[str] = "visualizations"
    endpoint_name: ClassVar[str] = "Visualizations"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter field returned in the response.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "title", "display_name": "Title"},
                    {
                        "value": "cluster_start",
                        "display_name": "Cluster start",
                    },
                    {"value": "cluster_end", "display_name": "Cluster end"},
                    {
                        "value": "json_versions",
                        "display_name": "Json versions",
                    },
                    {"value": "clusters", "display_name": "Clusters"},
                    {"value": "absolute_url", "display_name": "Absolute url"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {
                        "value": "date_published",
                        "display_name": "Date published",
                    },
                    {"value": "date_deleted", "display_name": "Date deleted"},
                    {"value": "slug", "display_name": "Slug"},
                    {"value": "notes", "display_name": "Notes"},
                    {"value": "view_count", "display_name": "View count"},
                    {"value": "published", "display_name": "Published"},
                    {"value": "deleted", "display_name": "Deleted"},
                    {
                        "value": "generation_time",
                        "display_name": "Generation time",
                    },
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
