"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import Annotated, ClassVar

from pydantic import AfterValidator, BeforeValidator, Field

from courtlistener.models.endpoint import Endpoint
from courtlistener.utils import (
    comma_separated_post_validator,
    comma_separated_pre_validator,
    multiple_choice_validator,
)


class VisualizationsJsonEndpoint(Endpoint):
    """Visualizations/Json Endpoint"""

    endpoint: ClassVar[str] = "/visualizations/json/"
    endpoint_id: ClassVar[str] = "visualizations/json"
    endpoint_name: ClassVar[str] = "Visualizations/Json"

    fields: Annotated[
        None | list[str],
        Field(
            None,
            description="Filter field returned in the response.",
            json_schema_extra={
                "choices": [
                    {"value": "resource_uri", "display_name": "Resource uri"},
                    {"value": "id", "display_name": "Id"},
                    {"value": "date_created", "display_name": "Date created"},
                    {
                        "value": "date_modified",
                        "display_name": "Date modified",
                    },
                    {"value": "json_data", "display_name": "Json data"},
                    {"value": "map", "display_name": "Map"},
                ],
            },
        ),
        AfterValidator(comma_separated_post_validator),
        BeforeValidator(multiple_choice_validator),
        BeforeValidator(comma_separated_pre_validator),
    ]
