"""
Please do not edit this file manually.
This file is automatically generated by the `scripts/generate_endpoints.py` script.
"""

from typing import ClassVar

from courtlistener.models.endpoint import Endpoint


class VisualizationsEndpoint(Endpoint):
    """Visualizations Endpoint"""

    endpoint: ClassVar[str] = "/visualizations/"
    endpoint_id: ClassVar[str] = "visualizations"
    endpoint_name: ClassVar[str] = "Visualizations"
