import subprocess

import unasync
from utils import BASE_DIR

ASYNC_DIR = BASE_DIR / "courtlistener" / "async_client"
SYNC_DIR = BASE_DIR / "courtlistener" / "sync_client"

REPLACEMENTS = {
    "async_client": "sync_client",
    "AsyncCourtListener": "CourtListener",
    "AsyncResource": "Resource",
    "AsyncResourceIterator": "ResourceIterator",
    "AsyncSearchAlerts": "SearchAlerts",
    "AsyncDocketAlerts": "DocketAlerts",
    "AsyncCitationLookup": "CitationLookup",
    "AsyncClient": "Client",
    "aclose": "close",
    "asyncio": "time",
}

GENERATED_NOTICE = '''"""
Please do not edit this file manually.
This file is automatically generated by `scripts/generate_sync_client.py`
from `courtlistener/async_client/{name}`.
"""

'''

WARNINGS_IMPORT_ANCHOR = "from __future__ import annotations\n\n"
DEPRECATED_ALIASES_ANCHOR = "\n\n\nclass Resource:"
DEPRECATED_ALIASES = '''    # ------------------------------------------------------------------
    # Deprecated property aliases, kept for backwards compatibility.
    # Use the get_* methods instead.
    # ------------------------------------------------------------------

    def _warn_deprecated(self, name: str) -> None:
        warnings.warn(
            f"ResourceIterator.{name} is deprecated and will be removed "
            f"in a future release; use get_{name}() instead.",
            DeprecationWarning,
            stacklevel=3,
        )

    @property
    def current_page(self) -> Page:
        """Deprecated alias for :meth:`get_current_page`."""
        self._warn_deprecated("current_page")
        return self.get_current_page()

    @property
    def count(self) -> int:
        """Deprecated alias for :meth:`get_count`."""
        self._warn_deprecated("count")
        return self.get_count()

    @property
    def document_count(self) -> int | None:
        """Deprecated alias for :meth:`get_document_count`."""
        self._warn_deprecated("document_count")
        return self.get_document_count()

    @property
    def results(self) -> list[dict[str, Any]]:
        """Deprecated alias for :meth:`get_results`."""
        self._warn_deprecated("results")
        return self.get_results()'''


def replace_once(text: str, anchor: str, replacement: str, name: str) -> str:
    if text.count(anchor) != 1:
        raise RuntimeError(
            f"Expected exactly one occurrence of {anchor!r} in the "
            f"generated {name}; the async source no longer matches the "
            "generator's post-processing anchors."
        )
    return text.replace(anchor, replacement)


def main() -> None:
    async_files = sorted(ASYNC_DIR.glob("*.py"))
    unasync.unasync_files(
        [str(path) for path in async_files],
        rules=[
            unasync.Rule(
                fromdir="/courtlistener/async_client/",
                todir="/courtlistener/sync_client/",
                additional_replacements=REPLACEMENTS,
            )
        ],
    )

    generated = [SYNC_DIR / path.name for path in async_files]
    for path in generated:
        text = GENERATED_NOTICE.format(name=path.name) + path.read_text()
        if path.name == "resource.py":
            text = replace_once(
                text,
                WARNINGS_IMPORT_ANCHOR,
                WARNINGS_IMPORT_ANCHOR + "import warnings\n",
                path.name,
            )
            text = replace_once(
                text,
                DEPRECATED_ALIASES_ANCHOR,
                "\n\n" + DEPRECATED_ALIASES + DEPRECATED_ALIASES_ANCHOR,
                path.name,
            )
        path.write_text(text)

    expected_files = {path.name for path in generated}
    for path in SYNC_DIR.glob("*.py"):
        if path.name not in expected_files:
            path.unlink()
            print(f"Removed stale {path.relative_to(BASE_DIR)}")

    subprocess.run(
        ["pre-commit", "run", "--files", *[str(path) for path in generated]],
        cwd=BASE_DIR,
        check=False,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    print(
        f"Generated {len(generated)} sync client files in "
        f"{SYNC_DIR.relative_to(BASE_DIR)}"
    )


if __name__ == "__main__":
    main()
