"""
Please do not edit this file manually.
This file is automatically generated by `scripts/generate_sync_client.py`
from `courtlistener/async_client/__init__.py`.
"""

from courtlistener.sync_client.alerts import (
    DocketAlerts,
    SearchAlerts,
)
from courtlistener.sync_client.citation_lookup import CitationLookup
from courtlistener.sync_client.client import CourtListener
from courtlistener.sync_client.prayers import Prayers
from courtlistener.sync_client.resource import (
    Resource,
    ResourceIterator,
)

__all__ = [
    "CitationLookup",
    "CourtListener",
    "DocketAlerts",
    "Prayers",
    "Resource",
    "ResourceIterator",
    "SearchAlerts",
]
