"""
Please do not edit this file manually.
This file is automatically generated by `scripts/generate_sync_client.py`
from `courtlistener/async_client/alerts.py`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

from courtlistener.models.alerts import (
    DocketAlertCreate,
    DocketAlertType,
    DocketAlertUpdate,
    RateType,
    SearchAlertCreate,
    SearchAlertType,
    SearchAlertUpdate,
)
from courtlistener.models.endpoints.alerts import AlertsEndpoint
from courtlistener.models.endpoints.docket_alerts import (
    DocketAlertsEndpoint,
)
from courtlistener.sync_client.resource import Resource

if TYPE_CHECKING:
    from courtlistener.sync_client.client import CourtListener


class SearchAlerts(Resource):
    """Helper for managing search alerts."""

    def __init__(self, client: CourtListener) -> None:
        super().__init__(client, AlertsEndpoint)

    def create(
        self,
        name: str,
        query: str | dict[str, Any],
        rate: RateType,
        alert_type: SearchAlertType | None = None,
    ) -> dict[str, Any]:
        """Create a new search alert."""
        validated = SearchAlertCreate(
            name=name, query=query, rate=rate, alert_type=alert_type
        )
        body = validated.model_dump(exclude_none=True)
        return cast(
            dict[str, Any],
            self._client._request("POST", self._endpoint, json=body),
        )

    def update(self, id: int, **data: Any) -> dict[str, Any]:
        """Update an existing search alert."""
        validated = SearchAlertUpdate(**data)
        body = validated.model_dump(exclude_none=True)
        return cast(
            dict[str, Any],
            self._client._request(
                "PATCH", f"{self._endpoint}{id}/", json=body
            ),
        )

    def delete(self, id: int) -> None:
        """Delete a search alert."""
        self._client._request("DELETE", f"{self._endpoint}{id}/")


class DocketAlerts(Resource):
    """Helper for managing docket alerts (subscriptions)."""

    def __init__(self, client: CourtListener) -> None:
        super().__init__(client, DocketAlertsEndpoint)

    def create(
        self, docket: int, alert_type: DocketAlertType = 1
    ) -> dict[str, Any]:
        """Create a new docket alert."""
        validated = DocketAlertCreate(docket=docket, alert_type=alert_type)
        return cast(
            dict[str, Any],
            self._client._request(
                "POST", self._endpoint, json=validated.model_dump()
            ),
        )

    def update(self, id: int, **data: Any) -> dict[str, Any]:
        """Update an existing docket alert."""
        validated = DocketAlertUpdate(**data)
        body = validated.model_dump(exclude_none=True)
        return cast(
            dict[str, Any],
            self._client._request(
                "PATCH", f"{self._endpoint}{id}/", json=body
            ),
        )

    def delete(self, id: int) -> None:
        """Delete a docket alert."""
        self._client._request("DELETE", f"{self._endpoint}{id}/")

    def subscribe(self, docket: int) -> dict[str, Any]:
        """Subscribe to a docket (convenience for create with type=1)."""
        for alert in self.list(docket=docket):
            return {**alert, "already_subscribed": True}

        return self.create(docket, alert_type=1)

    def unsubscribe(self, docket: int) -> None:
        """Unsubscribe from a docket by docket ID."""
        results = self.list(docket=docket)
        for alert in results:
            self.delete(alert["id"])
            return
        raise ValueError(f"No docket alert found for docket {docket}")
