"""
Please do not edit this file manually.
This file is automatically generated by `scripts/generate_sync_client.py`
from `courtlistener/async_client/api_usage.py`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

if TYPE_CHECKING:
    from courtlistener.sync_client.client import CourtListener


class ApiUsage:
    """Helper for the API usage endpoint.

    The endpoint has its own throttle scope, so it stays reachable when
    the main API quota is exhausted.
    """

    ENDPOINT = "/api-usage/"

    def __init__(self, client: CourtListener) -> None:
        self._client = client

    def get(self) -> dict[str, Any]:
        """Fetch the authenticated user's API usage and rate limits.

        Returns:
            Dict with ``current_usage``, one row per throttle scope and
            rate (``scope``, ``rate``, ``used``, ``limit``, ``remaining``,
            ``window_seconds``, ``reset_at``, ``blocked``);
            ``historical_usage``, daily request counts for the last 14
            days keyed by ISO date plus a ``total``; and ``membership``
            (``level`` and ``is_active``), or ``None`` without one.
        """
        return cast(
            dict[str, Any],
            self._client._request("GET", self.ENDPOINT),
        )
