"""
Please do not edit this file manually.
This file is automatically generated by `scripts/generate_sync_client.py`
from `courtlistener/async_client/prayers.py`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

from courtlistener.models.endpoints.prayers import PrayersEndpoint
from courtlistener.models.prayers import PrayerCreate
from courtlistener.sync_client.resource import Resource

if TYPE_CHECKING:
    from courtlistener.sync_client.client import CourtListener


class Prayers(Resource):
    """Helper for managing Pray and Pay requests."""

    def __init__(self, client: CourtListener) -> None:
        super().__init__(client, PrayersEndpoint)

    def create(self, recap_document: int) -> dict[str, Any]:
        """Create a new prayer for a RECAP document."""
        validated = PrayerCreate(recap_document=recap_document)
        return cast(
            dict[str, Any],
            self._client._request(
                "POST", self._endpoint, json=validated.model_dump()
            ),
        )

    def delete(self, id: int) -> None:
        """Delete a prayer that has not yet been granted."""
        self._client._request("DELETE", f"{self._endpoint}{id}/")
